### PR TITLE
chore(datastage): rm staging.datastage.io, decommissioned

### PR DESCRIPTION
**Pull request by vpsx**
~Fix ETL mapping errors raised by gen3utils validator~
rm staging.datastage.io, decommissioned

### CODE REVIEW

**Comment by vpsx** [comment]
`age_at_enrollment` is [already not present](https://github.com/uc-cdis/cdis-manifest/blob/5b01d3590a0d01deb9c3dbed5566dc3f2e6aa85c/preprod.gen3.biodatacatalyst.nhlbi.nih.gov/etlMapping.yaml#L70-L103) in the preprod etl mapping 🤷

**Comment by PlanXCyborg** [comment]
# staging.datastage.io/manifest.json
## :warning: Services on branch
- revproxy

**Comment by PlanXCyborg** [comment]
# staging.datastage.io/manifest.json
## :warning: Services on branch
- revproxy
# staging.gen3.biodatacatalyst.nhlbi.nih.gov/manifest.json
## :warning: Services on branch
- revproxy

**Comment by PlanXCyborg** [comment]
# staging.datastage.io/manifest.json
## :warning: Services on branch
- revproxy
# staging.gen3.biodatacatalyst.nhlbi.nih.gov/manifest.json
## :warning: Services on branch
- revproxy

**Comment by PlanXCyborg** [comment]
# staging.datastage.io/manifest.json
## :warning: Services on branch
- revproxy

**Comment by PlanXCyborg** [comment]
# staging.datastage.io/manifest.json
## :warning: Services on branch
- revproxy

**Pull request merged**
