### PR TITLE
dataguids.org Relative resolver URL.

### PR DESCRIPTION
**Pull request by paulineribeyre**
Link to Jira ticket if there is one:

see https://github.com/uc-cdis/dataguids.org/pull/4

### Environments
dataguids.org

### Description of changes
Relative resolver URL instead of absolute URL, to allow testing in jenkins

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# dataguids.org/manifest.json
## :warning: Services on branch
- portal
- revproxy

**Comment by PlanXCyborg** [comment]
# dataguids.org/manifest.json
## :warning: Services on branch
- revproxy

**Comment by PlanXCyborg** [comment]
# dataguids.org/manifest.json
## :warning: Services on branch
- revproxy
## Deployment changes
- indexd
  - Indexd's blank record endpoints now allow direct iteration from a user with their access token but requires the file upload arborist role to be modified so the service is not just `fence` but instead `*` so indexd works too. see https://github.com/uc-cdis/commons-users/pull/908/files for example (uc-cdis/uc-cdis/indexd#275)

**Comment by PlanXCyborg** [comment]
# dataguids.org/manifest.json
## :warning: Services on branch
- revproxy
## Deployment changes
- indexd
  - Indexd's blank record endpoints now allow direct iteration from a user with their access token but requires the file upload arborist role to be modified so the service is not just `fence` but instead `*` so indexd works too. see https://github.com/uc-cdis/commons-users/pull/908/files for example (uc-cdis/uc-cdis/indexd#275)

**Comment by PlanXCyborg** [comment]
# dataguids.org/manifest.json
## :warning: Services on branch
- revproxy
## Deployment changes
- indexd
  - Indexd's blank record endpoints now allow direct iteration from a user with their access token but requires the file upload arborist role to be modified so the service is not just `fence` but instead `*` so indexd works too. see https://github.com/uc-cdis/commons-users/pull/908/files for example (uc-cdis/uc-cdis/indexd#275)

**Comment by PlanXCyborg** [comment]
# dataguids.org/manifest.json
## :warning: Services on branch
- revproxy

**Comment by PlanXCyborg** [comment]
# dataguids.org/manifest.json
## :warning: Services on branch
- revproxy

**Comment by PlanXCyborg** [comment]
# dataguids.org/manifest.json
## :warning: Services on branch
- revproxy

**Comment by PlanXCyborg** [comment]
# dataguids.org/manifest.json
## :warning: Services on branch
- indexd
- revproxy

**Comment by PlanXCyborg** [comment]
# dataguids.org/manifest.json
## :warning: Services on branch
- indexd
- revproxy

**Review by jingh8 — APPROVED** [review]

**Pull request merged**
