### PR TITLE
Updating Env chicagoland.pandemicresponsecommons.org - 2022.11 1668114186

### PR DESCRIPTION
**Pull request by PlanXCyborg**
Applying version 2022.11 to chicagoland.pandemicresponsecommons.org

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# chicagoland.pandemicresponsecommons.org/manifest.json
## Deployment changes
- awshelper
  - Currently requires to manually update prisma api key in json format under this path in the adminvm (uc-cdis/cloud-automation#2061)
  - `~/Gen3Secrets/prisma/apikey.json` (uc-cdis/cloud-automation#2061)
  - format has to be the following: (uc-cdis/cloud-automation#2061)
  - ``` (uc-cdis/cloud-automation#2061)
  - { (uc-cdis/cloud-automation#2061)
  - "AccessKeyID": "XXXX", (uc-cdis/cloud-automation#2061)
  - "SecretKey": "XXXX" (uc-cdis/cloud-automation#2061)
  - } (uc-cdis/cloud-automation#2061)
  - ``` (uc-cdis/cloud-automation#2061)
  - This PR extends `kube-setup-hatchery` to create a kubernetes secret with for prisma cloud credentials, and extending the hatchery deployment to look for this secret and use it, if it exists. (uc-cdis/cloud-automation#2061)
- fence
  - Configure the `ALLOWED_DATA_UPLOAD_BUCKETS` setting to allow users to upload to buckets other than `DATA_UPLOAD_BUCKET` (uc-cdis/fence#1051)
  - B/c the default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP, you MUST ensure that an instance that should comply with FedRAMP does NOT override this fence configuration (e.g. it should be 15 minutes) `SESSION_TIMEOUT: 900` (uc-cdis/fence#1040)
- metadata
  - configuration files will need to be updated (uc-cdis/metadata-service#65)
  - Database migration for MDS (uc-cdis/metadata-service#63)
## Breaking changes
- arborist
  - The `GET /auth/mapping` endpoint does not accept `username` as a query parameter anymore. It only supports parsing the username from the provided JWT. To specify a username, use the `POST /auth/mapping` endpoint. (uc-cdis/arborist#153)
- fence
  - Default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP (uc-cdis/fence#1040)
- indexd
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (uc-cdis/indexd#336)
- metadata
  - The configuration file is not compatible with the previous release. This is due to the new support for defining a schema, new configuration options, and changes to the adapters. (uc-cdis/metadata-service#65)

**Review by paulineribeyre — DISMISSED** [review]

**Comment by paulineribeyre** [comment]
Please review: https://github.com/uc-cdis/gitops-qa/pull/2327

**Comment by PlanXCyborg** [comment]
# chicagoland.pandemicresponsecommons.org/manifest.json
## Deployment changes
- awshelper
  - To set up the `metadata-delete-expired-objects` job, run the `gen3 kube-setup-metadata-delete-expired-objects-cronjob` command. Note that the `metadata-delete-expired-objects-job` client must be granted access to `(resource=/mds_gateway, method=access, service=mds_gateway)` and `(resource=/programs, method=delete, service=fence)` (https://github.com/uc-cdis/cloud-automation/pull/1941)
  - [PXP-9516]: https://ctds-planx.atlassian.net/browse/PXP-9516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ (https://github.com/uc-cdis/cloud-automation/pull/1941)
  - Currently requires to manually update prisma api key in json format under this path in the adminvm (https://github.com/uc-cdis/cloud-automation/pull/2061)
  - `~/Gen3Secrets/prisma/apikey.json` (https://github.com/uc-cdis/cloud-automation/pull/2061)
  - format has to be the following: (https://github.com/uc-cdis/cloud-automation/pull/2061)
  - ``` (https://github.com/uc-cdis/cloud-automation/pull/2061)
  - { (https://github.com/uc-cdis/cloud-automation/pull/2061)
  - "AccessKeyID": "XXXX", (https://github.com/uc-cdis/cloud-automation/pull/2061)
  - "SecretKey": "XXXX" (https://github.com/uc-cdis/cloud-automation/pull/2061)
  - } (https://github.com/uc-cdis/cloud-automation/pull/2061)
  - ``` (https://github.com/uc-cdis/cloud-automation/pull/2061)
  - This PR extends `kube-setup-hatchery` to create a kubernetes secret with for prisma cloud credentials, and extending the hatchery deployment to look for this secret and use it, if it exists. (https://github.com/uc-cdis/cloud-automation/pull/2061)
- dashboard
  - This change will add some CSP and CORS related header to the response that returned from the dashboard services. They should not be interruptive, but each team is encouraged to double check their webpages hosted by dashboard to ensure they still works (https://github.com/uc-cdis/gen3-statics/pull/27)
  - Because of these CSP directives being added, starting from this version, if anyone what to load remote scripts in their dashboard-hosted webpages, they will need to update the CSP directives in this dashboard service if the current directives doesn't fit, or to ship the script files with the page (https://github.com/uc-cdis/gen3-statics/pull/27)
  - [PPS-154]: https://ctds-planx.atlassian.net/browse/PPS-154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ (https://github.com/uc-cdis/gen3-statics/pull/27)
- fence
  - Configure the `ALLOWED_DATA_UPLOAD_BUCKETS` setting to allow users to upload to buckets other than `DATA_UPLOAD_BUCKET` (https://github.com/uc-cdis/fence/pull/1051)
  - B/c the default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP, you MUST ensure that an instance that should comply with FedRAMP does NOT override this fence configuration (e.g. it should be 15 minutes) `SESSION_TIMEOUT: 900` (https://github.com/uc-cdis/fence/pull/1040)
- metadata
  - configuration files will need to be updated (https://github.com/uc-cdis/metadata-service/pull/65)
  - Database migration for MDS (https://github.com/uc-cdis/metadata-service/pull/63)
- portal
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)
- sower
  - [PPS-169]: https://ctds-planx.atlassian.net/browse/PPS-169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ (https://github.com/uc-cdis/sower/pull/36)
- ssjdispatcher
  - [PPS-169]: https://ctds-planx.atlassian.net/browse/PPS-169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ (https://github.com/uc-cdis/ssjdispatcher/pull/46)
- tube
  - [PXP-10516]: https://ctds-planx.atlassian.net/browse/PXP-10516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ (https://github.com/uc-cdis/tube/pull/220)
## Breaking changes
- arborist
  - The `GET /auth/mapping` endpoint does not accept `username` as a query parameter anymore. It only supports parsing the username from the provided JWT. To specify a username, use the `POST /auth/mapping` endpoint. (https://github.com/uc-cdis/arborist/pull/153)
- fence
  - Default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP (https://github.com/uc-cdis/fence/pull/1040)
- indexd
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (https://github.com/uc-cdis/indexd/pull/338)
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (https://github.com/uc-cdis/indexd/pull/336)
- metadata
  - The configuration file is not compatible with the previous release. This is due to the new support for defining a schema, new configuration options, and changes to the adapters. (https://github.com/uc-cdis/metadata-service/pull/65)

**Comment by PlanXCyborg** [comment]
# chicagoland.pandemicresponsecommons.org/manifest.json
## Deployment changes
- awshelper
  - To set up the `metadata-delete-expired-objects` job, run the `gen3 kube-setup-metadata-delete-expired-objects-cronjob` command. Note that the `metadata-delete-expired-objects-job` client must be granted access to `(resource=/mds_gateway, method=access, service=mds_gateway)` and `(resource=/programs, method=delete, service=fence)` (https://github.com/uc-cdis/cloud-automation/pull/1941)
  - [PXP-9516]: https://ctds-planx.atlassian.net/browse/PXP-9516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ (https://github.com/uc-cdis/cloud-automation/pull/1941)
  - Currently requires to manually update prisma api key in json format under this path in the adminvm (https://github.com/uc-cdis/cloud-automation/pull/2061)
  - `~/Gen3Secrets/prisma/apikey.json` (https://github.com/uc-cdis/cloud-automation/pull/2061)
  - format has to be the following: (https://github.com/uc-cdis/cloud-automation/pull/2061)
  - ``` (https://github.com/uc-cdis/cloud-automation/pull/2061)
  - { (https://github.com/uc-cdis/cloud-automation/pull/2061)
  - "AccessKeyID": "XXXX", (https://github.com/uc-cdis/cloud-automation/pull/2061)
  - "SecretKey": "XXXX" (https://github.com/uc-cdis/cloud-automation/pull/2061)
  - } (https://github.com/uc-cdis/cloud-automation/pull/2061)
  - ``` (https://github.com/uc-cdis/cloud-automation/pull/2061)
  - This PR extends `kube-setup-hatchery` to create a kubernetes secret with for prisma cloud credentials, and extending the hatchery deployment to look for this secret and use it, if it exists. (https://github.com/uc-cdis/cloud-automation/pull/2061)
- dashboard
  - This change will add some CSP and CORS related header to the response that returned from the dashboard services. They should not be interruptive, but each team is encouraged to double check their webpages hosted by dashboard to ensure they still works (https://github.com/uc-cdis/gen3-statics/pull/27)
  - Because of these CSP directives being added, starting from this version, if anyone what to load remote scripts in their dashboard-hosted webpages, they will need to update the CSP directives in this dashboard service if the current directives doesn't fit, or to ship the script files with the page (https://github.com/uc-cdis/gen3-statics/pull/27)
  - [PPS-154]: https://ctds-planx.atlassian.net/browse/PPS-154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ (https://github.com/uc-cdis/gen3-statics/pull/27)
- fence
  - Configure the `ALLOWED_DATA_UPLOAD_BUCKETS` setting to allow users to upload to buckets other than `DATA_UPLOAD_BUCKET` (https://github.com/uc-cdis/fence/pull/1051)
  - B/c the default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP, you MUST ensure that an instance that should comply with FedRAMP does NOT override this fence configuration (e.g. it should be 15 minutes) `SESSION_TIMEOUT: 900` (https://github.com/uc-cdis/fence/pull/1040)
- metadata
  - configuration files will need to be updated (https://github.com/uc-cdis/metadata-service/pull/65)
  - Database migration for MDS (https://github.com/uc-cdis/metadata-service/pull/63)
- portal
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)
- sower
  - [PPS-169]: https://ctds-planx.atlassian.net/browse/PPS-169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ (https://github.com/uc-cdis/sower/pull/36)
- ssjdispatcher
  - [PPS-169]: https://ctds-planx.atlassian.net/browse/PPS-169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ (https://github.com/uc-cdis/ssjdispatcher/pull/46)
- tube
  - [PXP-10516]: https://ctds-planx.atlassian.net/browse/PXP-10516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ (https://github.com/uc-cdis/tube/pull/220)
## Breaking changes
- arborist
  - The `GET /auth/mapping` endpoint does not accept `username` as a query parameter anymore. It only supports parsing the username from the provided JWT. To specify a username, use the `POST /auth/mapping` endpoint. (https://github.com/uc-cdis/arborist/pull/153)
- fence
  - Default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP (https://github.com/uc-cdis/fence/pull/1040)
- indexd
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (https://github.com/uc-cdis/indexd/pull/338)
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (https://github.com/uc-cdis/indexd/pull/336)
- metadata
  - The configuration file is not compatible with the previous release. This is due to the new support for defining a schema, new configuration options, and changes to the adapters. (https://github.com/uc-cdis/metadata-service/pull/65)

**Review by paulineribeyre — APPROVED** [review]

**Pull request merged**
