### PR TITLE
chore: adding nightly env to the list

### PR DESCRIPTION
**Pull request by atharvar28**
Adding `nightly.planx-pla.net` to run test on nightly basis

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# nightly.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- audit-service
- awshelper
- fence
- indexd
- mariner
- ws-storage
- peregrine
- pidgin
- revproxy
- sheepdog
- portal
- spark
- ssjdispatcher
- tube
- manifestservice
- wts
- guppy
- sower
- hatchery
- metadata
- dashboard
- requestor

**Comment by PlanXCyborg** [comment]
# nightly.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- audit-service
- awshelper
- fence
- indexd
- mariner
- ws-storage
- peregrine
- pidgin
- revproxy
- sheepdog
- portal
- spark
- ssjdispatcher
- tube
- manifestservice
- wts
- guppy
- sower
- hatchery
- metadata
- dashboard
- requestor

**Comment by PlanXCyborg** [comment]
# nightly.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- audit-service
- awshelper
- fence
- indexd
- mariner
- ws-storage
- peregrine
- pidgin
- revproxy
- sheepdog
- portal
- spark
- ssjdispatcher
- tube
- manifestservice
- wts
- guppy
- sower
- hatchery
- metadata
- dashboard
- requestor

**Comment by PlanXCyborg** [comment]
# nightly.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- audit-service
- awshelper
- fence
- indexd
- mariner
- ws-storage
- peregrine
- pidgin
- revproxy
- sheepdog
- portal
- spark
- ssjdispatcher
- tube
- manifestservice
- wts
- guppy
- sower
- hatchery
- metadata
- dashboard
- requestor

**Comment by PlanXCyborg** [comment]
# nightly.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- audit-service
- awshelper
- fence
- indexd
- mariner
- ws-storage
- peregrine
- pidgin
- revproxy
- sheepdog
- portal
- spark
- ssjdispatcher
- tube
- manifestservice
- wts
- guppy
- sower
- hatchery
- metadata
- dashboard
- requestor

**Review by emalinowski — APPROVED** [review]

**Review by themarcelor — APPROVED** [review]
+1

**Comment by PlanXCyborg** [comment]
# nightly.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- audit-service
- awshelper
- fence
- indexd
- mariner
- ws-storage
- peregrine
- pidgin
- revproxy
- sheepdog
- portal
- spark
- ssjdispatcher
- tube
- manifestservice
- wts
- guppy
- sower
- hatchery
- metadata
- dashboard
- requestor

**Pull request merged**
