### PR TITLE
upgrade services to 2021.08

### PR DESCRIPTION
**Pull request by haraprasadj**
Link to Jira ticket if there is one:

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# healdata.org/manifest.json
## :warning: Services on branch
- hatchery

**Comment by PlanXCyborg** [comment]
# healdata.org/manifest.json
## :warning: Services on branch
- hatchery
# preprod.healdata.org/manifest.json
## :warning: Services on branch
- hatchery

**Comment by PlanXCyborg** [comment]
# healdata.org/manifest.json
## :warning: Services on branch
- hatchery
## Deployment changes
- metadata
  - A job has been created to make aggregate MDS population more robust https://github.com/uc-cdis/cloud-automation/pull/1722 (uc-cdis/metadata-service#33)

**Comment by PlanXCyborg** [comment]
# healdata.org/manifest.json
## :warning: Services on branch
- hatchery
## Deployment changes
- metadata
  - A job has been created to make aggregate MDS population more robust https://github.com/uc-cdis/cloud-automation/pull/1722 (uc-cdis/metadata-service#33)

**Comment by PlanXCyborg** [comment]
# healdata.org/manifest.json
## :warning: Services on branch
- hatchery
## Deployment changes
- metadata
  - A job has been created to make aggregate MDS population more robust https://github.com/uc-cdis/cloud-automation/pull/1722 (uc-cdis/metadata-service#33)

**Comment by PlanXCyborg** [comment]
# healdata.org/manifest.json
## :warning: Services on branch
- hatchery

**Review by nmetokishlubsky — APPROVED** [review]

**Pull request merged**
