### PR TITLE
Feature/BRH-264 BRH staging to prod

### PR DESCRIPTION
**Pull request by aartivnkt**
Link to Jira ticket if there is one:
https://ctds-planx.atlassian.net/browse/BRH-264

### Environments
BRH Prod

### Description of changes

1. BRH Documentation changes from staging to prod
2. Update two example analysis HTML notebooks (canine, how to access)
3. Update portal v to 5.0.0, kayako-wrapper to 0.1.1, requestor to 1.7.1 and wts to 0.4.1
4. Fix JCOIN commons_url bug in aggMDS config
5.  Update gitops.json to use aggWTS, workspace registration feature, update portal tags to show in description, other portal changes to data access method , tutorial notebook links, and workspace registration config updates in portal

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# brh.data-commons.org/manifest.json
## :warning: Services on branch
- metadata

**Comment by PlanXCyborg** [comment]
# brh.data-commons.org/manifest.json
## :warning: Services on branch
- metadata

**Review by nss10 — APPROVED** [review]
Everything w.r.t. Workspace registration looks good. To me.

**Review by jmontmaxwell — APPROVED** [review]

**Comment by menum724** [comment]
"Uc-cdis", Can you tell me more about this master? I want to help Kayako to maintain safety and balance in the end users UI n such. I am not sure about a lot of things though.

**Comment by menum724** [comment]
You can close my Pull Request. Thanks.

**Pull request merged**
