### PR TITLE
Gen3 Monthly Release 2020.09 gen3.datacommons.io 1598910416

### PR DESCRIPTION
**Pull request by themarcelor**
Applying version 2020.09 to gen3.datacommons.io

### CODE REVIEW

**Comment by mpingram** [comment]
This is deploying 2020.09, not 2020.10 FYI @themarcelor

**Review by cgmeyer — APPROVED** [review]
🍕

**Comment by mpingram** [comment]
Reverted your fix @themarcelor so that we don't accidentally merge the underscore fix with this 2020.09 PR

**Comment by mpingram** [comment]
Actually, closing -- 2020.10 is already in gen3.datacommons.io https://github.com/uc-cdis/cdis-manifest/pull/2134

**Pull request closed without merging**
