### PR TITLE
IL bayes model V2, virus ETL, NPI-PRO ETL

### PR DESCRIPTION
**Pull request by paulineribeyre**

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# chicagoland.pandemicresponsecommons.org/manifest.json
## :warning: Services on branch
- portal

**Comment by paulineribeyre** [comment]
DO NOT MERGE - waiting for new nb-etl release

**Comment by PlanXCyborg** [comment]
# chicagoland.pandemicresponsecommons.org/manifest.json
## :warning: Services on branch
- portal

**Comment by PlanXCyborg** [comment]
# chicagoland.pandemicresponsecommons.org/manifest.json
## :warning: Services on branch
- portal

**Comment by PlanXCyborg** [comment]
# chicagoland.pandemicresponsecommons.org/manifest.json
## :warning: Services on branch
- portal

**Pull request merged**
