### PR TITLE
PXP-6865 Copy from qa-niaid

### PR DESCRIPTION
**Pull request by paulineribeyre**
Link to Jira ticket if there is one: PXP-6865

### Environments
accessclinicaldata.niaid.nih.gov

### Description of changes
copy config from qa-niaid

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# accessclinicaldata.niaid.nih.gov/manifest.json
## :warning: Services on branch
- portal

**Comment by PlanXCyborg** [comment]
# accessclinicaldata.niaid.nih.gov/manifest.json
## :warning: Services on branch
- portal

**Review by atharvar28 — APPROVED** [review]
LGTM 👍

**Comment by PlanXCyborg** [comment]
# accessclinicaldata.niaid.nih.gov/manifest.json
## :warning: Services on branch
- portal

**Comment by paulineribeyre** [comment]
https://github.com/uc-cdis/gen3-qa/pull/468 to fix failed jenkins test

**Pull request merged**
