### PR TITLE
PXP-7947 KF external QA 2021.03 + audit-service + ECR images

### PR DESCRIPTION
**Pull request by paulineribeyre**
Link to Jira ticket if there is one: https://ctds-planx.atlassian.net/browse/PXP-7947

https://github.com/uc-cdis/gitops-qa/pull/1294
https://github.com/uc-cdis/cdis-manifest/pull/2779

### Environments
KF staging

### Description of changes
2021.03 + audit-service + latest fence with audit-service integration + ECR images

### CODE REVIEW

**Comment by paulineribeyre** [comment]
Reminder to check that `ENABLE_DB_MIGRATION` in disabled in the Fence config BEFORE merging, and to run the migration after merging

**Review by ocshawn — APPROVED** [review]
looks good to me

**Review by atharvar28 — APPROVED** [review]

**Comment by paulineribeyre** [comment]
waiting for sponsor green light

**Comment by paulineribeyre** [comment]
will deploy new versions instead

**Pull request closed without merging**
