### PR TITLE
Chore/fix gen3 datacommons dsc

### PR DESCRIPTION
**Pull request by xritter1**
Link to Jira ticket if there is one:

### Environments
oadc

### Description of changes
show the 3 studies hosted on the oadc for the discovery page. this relies on the data-portal branch https://github.com/uc-cdis/data-portal/compare/chore/fix_gen3_datacommons_dsc.

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# gen3.datacommons.io/manifest.json
## :warning: Services on branch
- portal

**Review by craigrbarnes — APPROVED** [review]
Removed my test in gitops.

**Comment by PlanXCyborg** [comment]
# gen3.datacommons.io/manifest.json
## :warning: Services on branch
- portal

**Review by cgmeyer — APPROVED** [review]
LGMT 🍕 🍺

**Pull request merged**
