### PR TITLE
Chore/logos

### PR DESCRIPTION
**Pull request by mfshao**
Link to Jira ticket if there is one:

### Environments
- various

### Description of changes
- apply new `gen3` and `createdby` logos

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# chorus.data-commons.org
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [node_id] in explorerConfig.charts not found in etlMapping

**Comment by PlanXCyborg** [comment]
# chorus.data-commons.org
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [node_id] in explorerConfig.charts not found in etlMapping

**Comment by PlanXCyborg** [comment]
# chorus.data-commons.org
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [node_id] in explorerConfig.charts not found in etlMapping

**Review by vzpgb — APPROVED** [review]

**Review by vzpgb — COMMENTED** [review]
Nice work!

I wonder if [brh.data-commons.org/dashboard/Public/img/gen3.png](https://github.com/uc-cdis/cdis-manifest/pull/5720/files#diff-9b90dee1d4ac28ec1bbb1e1ddc1bd2fec0768b52c434e4e34ca052b1f9a47720) should be white and blue instead of black and blue (the footer is dark and previous version is white and yellow)

And same with [brhstaging.data-commons.org/dashboard/Public/img/gen3.png](https://github.com/uc-cdis/cdis-manifest/pull/5720/files#diff-729c31e6315cea69348e269405bad404ca952afa838e05084615a54644b8a50d)

**Comment by mfshao** [comment]
> Nice work!
> 
> I wonder if [brh.data-commons.org/dashboard/Public/img/gen3.png](https://github.com/uc-cdis/cdis-manifest/pull/5720/files#diff-9b90dee1d4ac28ec1bbb1e1ddc1bd2fec0768b52c434e4e34ca052b1f9a47720) should be white and blue instead of black and blue (the footer is dark and previous version is white and yellow)
> 
> And same with [brhstaging.data-commons.org/dashboard/Public/img/gen3.png](https://github.com/uc-cdis/cdis-manifest/pull/5720/files#diff-729c31e6315cea69348e269405bad404ca952afa838e05084615a54644b8a50d)

no the pervious one is not right, and frankly those two pages are not being used by BRH anymore 🤷‍♂️

**Pull request merged**
