### PR TITLE
HEAL RELEASE 1622039500

### PR DESCRIPTION
**Pull request by themarcelor**
copying files from preprod.healdata.org to healdata.org

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# healdata.org/manifest.json
## :warning: Services on branch
- portal

**Comment by PlanXCyborg** [comment]
# healdata.org/manifest.json
## :warning: Services on branch
- portal

**Comment by PlanXCyborg** [comment]
# healdata.org/manifest.json
## :warning: Services on branch
- portal

**Review by xritter1 — APPROVED** [review]
lgtm

**Review by ac3eb — APPROVED** [review]
LGTM

**Pull request merged**
