### PR TITLE
Gen3 Monthly Release 2023.10 data.midrc.org 1696704880

### PR DESCRIPTION
**Pull request by PlanXCyborg**
Applying version 2023.10 to data.midrc.org

### CODE REVIEW

**Review by frankliuao — APPROVED** [review]
2023.10 Gen3 monthly release + sower update. Please merge. Approved.

**Review by frankliuao — CHANGES_REQUESTED** [review]
I forgot to check the dicom-viewer version. Could you update that?

**Review by frankliuao — APPROVED** [review]
Boosting OHIF from V2-->V3; deploying 2023.10 in production. Approved.

**Review by m0nhawk — APPROVED** [review]
👍

**Pull request merged**
