### PR TITLE
deploy vlmd sub

### PR DESCRIPTION
**Pull request by mfshao**
⚠️ **Must run AggMDS sync job after merging this PR and updating MDS**

Link to Jira ticket if there is one:

### Environments
- heal prod

### Description of changes
- deploy VLMD submission

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# healdata.org/manifest.json
## Deployment changes
- metadata
  - Envs using AggMDS before must run the AggMDS sync job after updating to this version to migrate AggMDS reocrds syntax (https://github.com/uc-cdis/metadata-service/pull/90)
## Breaking changes
- metadata
  - Data format of response returned from `/aggregate/metadata/guid/{guid}`  has changed, please refer to the PR description and/or API docs for details (https://github.com/uc-cdis/metadata-service/pull/90)
  - Data format of response returned from `/aggregate/metadata/{name}`  has changed, please refer to the PR description and/or API docs for details (https://github.com/uc-cdis/metadata-service/pull/90)

**Comment by PlanXCyborg** [comment]
# healdata.org/manifest.json
## Deployment changes
- metadata
  - Envs using AggMDS before must run the AggMDS sync job after updating to this version to migrate AggMDS reocrds syntax (https://github.com/uc-cdis/metadata-service/pull/90)
## Breaking changes
- metadata
  - Data format of response returned from `/aggregate/metadata/guid/{guid}`  has changed, please refer to the PR description and/or API docs for details (https://github.com/uc-cdis/metadata-service/pull/90)
  - Data format of response returned from `/aggregate/metadata/{name}`  has changed, please refer to the PR description and/or API docs for details (https://github.com/uc-cdis/metadata-service/pull/90)

**Comment by PlanXCyborg** [comment]
# healdata.org/manifest.json
## Deployment changes
- metadata
  - Envs using AggMDS before must run the AggMDS sync job after updating to this version to migrate AggMDS reocrds syntax (https://github.com/uc-cdis/metadata-service/pull/90)
## Breaking changes
- metadata
  - Data format of response returned from `/aggregate/metadata/guid/{guid}`  has changed, please refer to the PR description and/or API docs for details (https://github.com/uc-cdis/metadata-service/pull/90)
  - Data format of response returned from `/aggregate/metadata/{name}`  has changed, please refer to the PR description and/or API docs for details (https://github.com/uc-cdis/metadata-service/pull/90)
- sower.container.image.batch-export
  - update batch export job for MDS v3 AggMDS response syntax (https://github.com/uc-cdis/sower-jobs/pull/43)

**Comment by mfshao** [comment]
seems to be an CI issue, same release has been tested in preprod, I'll merge

**Review by hughestr — APPROVED** [review]

**Pull request merged**
