### PR TITLE
adding Argocd and WAF flags to all commons manifest.json to make them…

### PR DESCRIPTION
**Pull request by EliseCastle23**
adding Argocd and WAF flags to all commons manifest.json to make them easy to deploy. Please refer to GPE-682 and GPE-564.

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# chorus.data-commons.org
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [node_id] in explorerConfig.charts not found in etlMapping

**Comment by PlanXCyborg** [comment]
# gen3.datacommons.io
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [node_id] in explorerConfig.charts not found in etlMapping

**Comment by PlanXCyborg** [comment]
# ibdgc.datacommons.io
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: rowAccessor [project_id] not found in index with type project

**Comment by PlanXCyborg** [comment]
# caninedc.org
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [node_id] in explorerConfig.charts not found in etlMapping

**Comment by PlanXCyborg** [comment]
# vpodc.data-commons.org
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [patients] in explorerConfig.guppyConfig.dataType not found in etlMapping
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Days_To_Birth] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Days_To_Death] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [DeceasedFlag] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Ethnicity] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Gender] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Race] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [ActionableMutations.Lab] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [ActionableMutations.Gene] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [ActionableMutations.DaysFromAnchorDateToBxDate] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Multiplicitycounter] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.ICDOSite] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Radiation] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Chemotherapy] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.DaysFromAnchorDateToDiagnosisDate] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Gradedifferentiation] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Laterality] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Stagegroupbest] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.RadiationsurgerySequence] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Histologyicdo3X] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Lymphvascularinvasionl] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.SeerSummaryStage2000] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.PhysiciansStage] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.DaysFromAnchorDateToMostdefinitivesurgDate] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.ChemotherapyFac] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.TumorSize] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.SequenceNumber] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [Race] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [Ethnicity] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [Gender] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [ActionableMutations.Lab] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Multiplicitycounter] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [Oncology_Primary.ICDOSite] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [Chicago_ID] in explorerConfig.charts not found in etlMapping
- Field error: Field [Oncology_Primary.ICDOSite] in explorerConfig.charts not found in etlMapping
- Field error: Field [Oncology_Primary.Radiation] in explorerConfig.charts not found in etlMapping
- Field error: Field [Oncology_Primary.Chemotherapy] in explorerConfig.charts not found in etlMapping

**Comment by PlanXCyborg** [comment]
# chorus.data-commons.org
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [node_id] in explorerConfig.charts not found in etlMapping

**Comment by PlanXCyborg** [comment]
# gen3.datacommons.io/manifest.json
## :warning: Services on branch
- frontend-framework
# login.bionimbus.org/manifest.json
## :warning: Services on branch
- revproxy

**Comment by PlanXCyborg** [comment]
# gen3.datacommons.io
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [node_id] in explorerConfig.charts not found in etlMapping

**Comment by PlanXCyborg** [comment]
# ibdgc.datacommons.io
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: rowAccessor [project_id] not found in index with type project

**Comment by PlanXCyborg** [comment]
# vpodc.data-commons.org
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [patients] in explorerConfig.guppyConfig.dataType not found in etlMapping
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Days_To_Birth] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Days_To_Death] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [DeceasedFlag] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Ethnicity] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Gender] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Race] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [ActionableMutations.Lab] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [ActionableMutations.Gene] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [ActionableMutations.DaysFromAnchorDateToBxDate] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Multiplicitycounter] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.ICDOSite] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Radiation] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Chemotherapy] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.DaysFromAnchorDateToDiagnosisDate] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Gradedifferentiation] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Laterality] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Stagegroupbest] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.RadiationsurgerySequence] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Histologyicdo3X] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Lymphvascularinvasionl] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.SeerSummaryStage2000] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.PhysiciansStage] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.DaysFromAnchorDateToMostdefinitivesurgDate] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.ChemotherapyFac] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.TumorSize] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.SequenceNumber] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [Race] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [Ethnicity] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [Gender] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [ActionableMutations.Lab] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Multiplicitycounter] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [Oncology_Primary.ICDOSite] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [Chicago_ID] in explorerConfig.charts not found in etlMapping
- Field error: Field [Oncology_Primary.ICDOSite] in explorerConfig.charts not found in etlMapping
- Field error: Field [Oncology_Primary.Radiation] in explorerConfig.charts not found in etlMapping
- Field error: Field [Oncology_Primary.Chemotherapy] in explorerConfig.charts not found in etlMapping

**Comment by PlanXCyborg** [comment]
# gen3.datacommons.io/manifest.json
## :warning: Services on branch
- frontend-framework
# login.bionimbus.org/manifest.json
## :warning: Services on branch
- revproxy

**Review by jawadqur — APPROVED** [review]

**Comment by PlanXCyborg** [comment]
# caninedc.org
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [node_id] in explorerConfig.charts not found in etlMapping

**Comment by PlanXCyborg** [comment]
# chorus.data-commons.org
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [node_id] in explorerConfig.charts not found in etlMapping

**Comment by PlanXCyborg** [comment]
# gen3.datacommons.io
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [node_id] in explorerConfig.charts not found in etlMapping

**Comment by PlanXCyborg** [comment]
# ibdgc.datacommons.io
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: rowAccessor [project_id] not found in index with type project

**Comment by PlanXCyborg** [comment]
# icgc.bionimbus.org
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [node_id] in explorerConfig.charts not found in etlMapping

**Comment by PlanXCyborg** [comment]
# vpodc.data-commons.org
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [patients] in explorerConfig.guppyConfig.dataType not found in etlMapping
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Days_To_Birth] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Days_To_Death] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [DeceasedFlag] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Ethnicity] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Gender] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Race] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [ActionableMutations.Lab] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [ActionableMutations.Gene] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [ActionableMutations.DaysFromAnchorDateToBxDate] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Multiplicitycounter] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.ICDOSite] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Radiation] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Chemotherapy] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.DaysFromAnchorDateToDiagnosisDate] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Gradedifferentiation] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Laterality] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Stagegroupbest] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.RadiationsurgerySequence] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Histologyicdo3X] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Lymphvascularinvasionl] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.SeerSummaryStage2000] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.PhysiciansStage] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.DaysFromAnchorDateToMostdefinitivesurgDate] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.ChemotherapyFac] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.TumorSize] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.SequenceNumber] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [Race] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [Ethnicity] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [Gender] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [ActionableMutations.Lab] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Multiplicitycounter] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [Oncology_Primary.ICDOSite] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [Chicago_ID] in explorerConfig.charts not found in etlMapping
- Field error: Field [Oncology_Primary.ICDOSite] in explorerConfig.charts not found in etlMapping
- Field error: Field [Oncology_Primary.Radiation] in explorerConfig.charts not found in etlMapping
- Field error: Field [Oncology_Primary.Chemotherapy] in explorerConfig.charts not found in etlMapping

**Comment by PlanXCyborg** [comment]
# gen3.datacommons.io/manifest.json
## :warning: Services on branch
- frontend-framework
## :warning: Services are being downgraded
- wts
- manifestservice
- revproxy
- sower
- pidgin
- guppy
- portal
- indexd
- metadata
- sheepdog
- arborist
- fence
- peregrine
- hatchery
- dashboard
- ssjdispatcher
- tube
- spark
## Deployment changes
- dashboard
  - This change will add some CSP and CORS related header to the response that returned from the dashboard services. They should not be interruptive, but each team is encouraged to double check their webpages hosted by dashboard to ensure they still works (https://github.com/uc-cdis/gen3-statics/pull/27)
  - Because of these CSP directives being added, starting from this version, if anyone what to load remote scripts in their dashboard-hosted webpages, they will need to update the CSP directives in this dashboard service if the current directives doesn't fit, or to ship the script files with the page (https://github.com/uc-cdis/gen3-statics/pull/27)
  - [PPS-154]: https://ctds-planx.atlassian.net/browse/PPS-154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ (https://github.com/uc-cdis/gen3-statics/pull/27)
- sower
  - [PPS-169]: https://ctds-planx.atlassian.net/browse/PPS-169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ (https://github.com/uc-cdis/sower/pull/36)
- ssjdispatcher
  - [PPS-169]: https://ctds-planx.atlassian.net/browse/PPS-169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ (https://github.com/uc-cdis/ssjdispatcher/pull/46)
- tube
  - [PXP-10516]: https://ctds-planx.atlassian.net/browse/PXP-10516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ (https://github.com/uc-cdis/tube/pull/220)
# login.bionimbus.org/manifest.json
## :warning: Services on branch
- revproxy

**Pull request merged**
