### PR TITLE
CHoRUS 2023.02 2023.02 chorus.data-commons.org 1675186471

### PR DESCRIPTION
**Pull request by PlanXCyborg**
Applying version 2023.02 to chorus.data-commons.org

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# chorus.data-commons.org
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [node_id] in explorerConfig.charts not found in etlMapping

**Comment by PlanXCyborg** [comment]
# chorus.data-commons.org/manifest.json
## Deployment changes
- dashboard
  - This change will add some CSP and CORS related header to the response that returned from the dashboard services. They should not be interruptive, but each team is encouraged to double check their webpages hosted by dashboard to ensure they still works (https://github.com/uc-cdis/gen3-statics/pull/27)
  - Because of these CSP directives being added, starting from this version, if anyone what to load remote scripts in their dashboard-hosted webpages, they will need to update the CSP directives in this dashboard service if the current directives doesn't fit, or to ship the script files with the page (https://github.com/uc-cdis/gen3-statics/pull/27)
- fence
  - Requires a Fence DB migration (https://github.com/uc-cdis/fence/pull/1068)
  - Configure the `ALLOWED_DATA_UPLOAD_BUCKETS` setting to allow users to upload to buckets other than `DATA_UPLOAD_BUCKET` (https://github.com/uc-cdis/fence/pull/1051)
  - B/c the default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP, you MUST ensure that an instance that should comply with FedRAMP does NOT override this fence configuration (e.g. it should be 15 minutes) `SESSION_TIMEOUT: 900` (https://github.com/uc-cdis/fence/pull/1040)
- portal
  - New portal config options to exclude File nodes from the charts added: use `"graphql.chartNodesExcludeFiles"` to exclude File nodes from graphql chart, or use `"components.index.homepageChartNodesExcludeFiles"` to exclude File nodes from homepage chart. Note both of them are default to `false` so you have to explicitly set them to `true` to enable them (https://github.com/uc-cdis/data-portal/pull/1208)
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)
## Breaking changes
- arborist
  - The `GET /auth/mapping` endpoint does not accept `username` as a query parameter anymore. It only supports parsing the username from the provided JWT. To specify a username, use the `POST /auth/mapping` endpoint. (https://github.com/uc-cdis/arborist/pull/153)
- fence
  - Default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP (https://github.com/uc-cdis/fence/pull/1040)
- indexd
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (https://github.com/uc-cdis/indexd/pull/338)
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (https://github.com/uc-cdis/indexd/pull/336)

**Comment by PlanXCyborg** [comment]
# chorus.data-commons.org
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [node_id] in explorerConfig.charts not found in etlMapping

**Comment by PlanXCyborg** [comment]
# chorus.data-commons.org/manifest.json
## Deployment changes
- dashboard
  - This change will add some CSP and CORS related header to the response that returned from the dashboard services. They should not be interruptive, but each team is encouraged to double check their webpages hosted by dashboard to ensure they still works (https://github.com/uc-cdis/gen3-statics/pull/27)
  - Because of these CSP directives being added, starting from this version, if anyone what to load remote scripts in their dashboard-hosted webpages, they will need to update the CSP directives in this dashboard service if the current directives doesn't fit, or to ship the script files with the page (https://github.com/uc-cdis/gen3-statics/pull/27)
- fence
  - Requires a Fence DB migration (https://github.com/uc-cdis/fence/pull/1068)
  - Configure the `ALLOWED_DATA_UPLOAD_BUCKETS` setting to allow users to upload to buckets other than `DATA_UPLOAD_BUCKET` (https://github.com/uc-cdis/fence/pull/1051)
  - B/c the default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP, you MUST ensure that an instance that should comply with FedRAMP does NOT override this fence configuration (e.g. it should be 15 minutes) `SESSION_TIMEOUT: 900` (https://github.com/uc-cdis/fence/pull/1040)
- portal
  - New portal config options to exclude File nodes from the charts added: use `"graphql.chartNodesExcludeFiles"` to exclude File nodes from graphql chart, or use `"components.index.homepageChartNodesExcludeFiles"` to exclude File nodes from homepage chart. Note both of them are default to `false` so you have to explicitly set them to `true` to enable them (https://github.com/uc-cdis/data-portal/pull/1208)
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)
## Breaking changes
- arborist
  - The `GET /auth/mapping` endpoint does not accept `username` as a query parameter anymore. It only supports parsing the username from the provided JWT. To specify a username, use the `POST /auth/mapping` endpoint. (https://github.com/uc-cdis/arborist/pull/153)
- fence
  - Default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP (https://github.com/uc-cdis/fence/pull/1040)
- indexd
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (https://github.com/uc-cdis/indexd/pull/338)
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (https://github.com/uc-cdis/indexd/pull/336)

**Comment by PlanXCyborg** [comment]
# chorus.data-commons.org
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [node_id] in explorerConfig.charts not found in etlMapping

**Review by trevars — APPROVED** [review]

**Comment by PlanXCyborg** [comment]
# chorus.data-commons.org/manifest.json
## Deployment changes
- dashboard
  - This change will add some CSP and CORS related header to the response that returned from the dashboard services. They should not be interruptive, but each team is encouraged to double check their webpages hosted by dashboard to ensure they still works (https://github.com/uc-cdis/gen3-statics/pull/27)
  - Because of these CSP directives being added, starting from this version, if anyone what to load remote scripts in their dashboard-hosted webpages, they will need to update the CSP directives in this dashboard service if the current directives doesn't fit, or to ship the script files with the page (https://github.com/uc-cdis/gen3-statics/pull/27)
- fence
  - Requires a Fence DB migration (https://github.com/uc-cdis/fence/pull/1068)
  - Configure the `ALLOWED_DATA_UPLOAD_BUCKETS` setting to allow users to upload to buckets other than `DATA_UPLOAD_BUCKET` (https://github.com/uc-cdis/fence/pull/1051)
  - B/c the default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP, you MUST ensure that an instance that should comply with FedRAMP does NOT override this fence configuration (e.g. it should be 15 minutes) `SESSION_TIMEOUT: 900` (https://github.com/uc-cdis/fence/pull/1040)
- portal
  - New portal config options to exclude File nodes from the charts added: use `"graphql.chartNodesExcludeFiles"` to exclude File nodes from graphql chart, or use `"components.index.homepageChartNodesExcludeFiles"` to exclude File nodes from homepage chart. Note both of them are default to `false` so you have to explicitly set them to `true` to enable them (https://github.com/uc-cdis/data-portal/pull/1208)
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)
## Breaking changes
- arborist
  - The `GET /auth/mapping` endpoint does not accept `username` as a query parameter anymore. It only supports parsing the username from the provided JWT. To specify a username, use the `POST /auth/mapping` endpoint. (https://github.com/uc-cdis/arborist/pull/153)
- fence
  - Default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP (https://github.com/uc-cdis/fence/pull/1040)
- indexd
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (https://github.com/uc-cdis/indexd/pull/338)
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (https://github.com/uc-cdis/indexd/pull/336)

**Comment by PlanXCyborg** [comment]
# chorus.data-commons.org
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [node_id] in explorerConfig.charts not found in etlMapping

**Comment by PlanXCyborg** [comment]
# chorus.data-commons.org/manifest.json
## Deployment changes
- dashboard
  - This change will add some CSP and CORS related header to the response that returned from the dashboard services. They should not be interruptive, but each team is encouraged to double check their webpages hosted by dashboard to ensure they still works (https://github.com/uc-cdis/gen3-statics/pull/27)
  - Because of these CSP directives being added, starting from this version, if anyone what to load remote scripts in their dashboard-hosted webpages, they will need to update the CSP directives in this dashboard service if the current directives doesn't fit, or to ship the script files with the page (https://github.com/uc-cdis/gen3-statics/pull/27)
- fence
  - Requires a Fence DB migration (https://github.com/uc-cdis/fence/pull/1068)
  - Configure the `ALLOWED_DATA_UPLOAD_BUCKETS` setting to allow users to upload to buckets other than `DATA_UPLOAD_BUCKET` (https://github.com/uc-cdis/fence/pull/1051)
  - B/c the default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP, you MUST ensure that an instance that should comply with FedRAMP does NOT override this fence configuration (e.g. it should be 15 minutes) `SESSION_TIMEOUT: 900` (https://github.com/uc-cdis/fence/pull/1040)
- portal
  - New portal config options to exclude File nodes from the charts added: use `"graphql.chartNodesExcludeFiles"` to exclude File nodes from graphql chart, or use `"components.index.homepageChartNodesExcludeFiles"` to exclude File nodes from homepage chart. Note both of them are default to `false` so you have to explicitly set them to `true` to enable them (https://github.com/uc-cdis/data-portal/pull/1208)
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)
## Breaking changes
- arborist
  - The `GET /auth/mapping` endpoint does not accept `username` as a query parameter anymore. It only supports parsing the username from the provided JWT. To specify a username, use the `POST /auth/mapping` endpoint. (https://github.com/uc-cdis/arborist/pull/153)
- fence
  - Default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP (https://github.com/uc-cdis/fence/pull/1040)
- indexd
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (https://github.com/uc-cdis/indexd/pull/338)
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (https://github.com/uc-cdis/indexd/pull/336)

**Comment by PlanXCyborg** [comment]
# chorus.data-commons.org
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [node_id] in explorerConfig.charts not found in etlMapping

**Comment by PlanXCyborg** [comment]
# chorus.data-commons.org/manifest.json
## Deployment changes
- dashboard
  - This change will add some CSP and CORS related header to the response that returned from the dashboard services. They should not be interruptive, but each team is encouraged to double check their webpages hosted by dashboard to ensure they still works (https://github.com/uc-cdis/gen3-statics/pull/27)
  - Because of these CSP directives being added, starting from this version, if anyone what to load remote scripts in their dashboard-hosted webpages, they will need to update the CSP directives in this dashboard service if the current directives doesn't fit, or to ship the script files with the page (https://github.com/uc-cdis/gen3-statics/pull/27)
- fence
  - Requires a Fence DB migration (https://github.com/uc-cdis/fence/pull/1068)
  - Configure the `ALLOWED_DATA_UPLOAD_BUCKETS` setting to allow users to upload to buckets other than `DATA_UPLOAD_BUCKET` (https://github.com/uc-cdis/fence/pull/1051)
  - B/c the default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP, you MUST ensure that an instance that should comply with FedRAMP does NOT override this fence configuration (e.g. it should be 15 minutes) `SESSION_TIMEOUT: 900` (https://github.com/uc-cdis/fence/pull/1040)
- portal
  - New portal config options to exclude File nodes from the charts added: use `"graphql.chartNodesExcludeFiles"` to exclude File nodes from graphql chart, or use `"components.index.homepageChartNodesExcludeFiles"` to exclude File nodes from homepage chart. Note both of them are default to `false` so you have to explicitly set them to `true` to enable them (https://github.com/uc-cdis/data-portal/pull/1208)
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)
- sheepdog
  - Sheepdog does not rely on configuration files in the cloud-automation repository anymore. The Sheepdog configuration files are in the Sheepdog repository. (https://github.com/uc-cdis/sheepdog/pull/387)
## Breaking changes
- arborist
  - The `GET /auth/mapping` endpoint does not accept `username` as a query parameter anymore. It only supports parsing the username from the provided JWT. To specify a username, use the `POST /auth/mapping` endpoint. (https://github.com/uc-cdis/arborist/pull/153)
- fence
  - Default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP (https://github.com/uc-cdis/fence/pull/1040)
- indexd
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (https://github.com/uc-cdis/indexd/pull/338)
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (https://github.com/uc-cdis/indexd/pull/336)

**Comment by PlanXCyborg** [comment]
# chorus.data-commons.org
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [node_id] in explorerConfig.charts not found in etlMapping

**Comment by PlanXCyborg** [comment]
# chorus.data-commons.org/manifest.json
## Deployment changes
- dashboard
  - This change will add some CSP and CORS related header to the response that returned from the dashboard services. They should not be interruptive, but each team is encouraged to double check their webpages hosted by dashboard to ensure they still works (https://github.com/uc-cdis/gen3-statics/pull/27)
  - Because of these CSP directives being added, starting from this version, if anyone what to load remote scripts in their dashboard-hosted webpages, they will need to update the CSP directives in this dashboard service if the current directives doesn't fit, or to ship the script files with the page (https://github.com/uc-cdis/gen3-statics/pull/27)
- fence
  - Requires a Fence DB migration (https://github.com/uc-cdis/fence/pull/1068)
  - Configure the `ALLOWED_DATA_UPLOAD_BUCKETS` setting to allow users to upload to buckets other than `DATA_UPLOAD_BUCKET` (https://github.com/uc-cdis/fence/pull/1051)
  - B/c the default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP, you MUST ensure that an instance that should comply with FedRAMP does NOT override this fence configuration (e.g. it should be 15 minutes) `SESSION_TIMEOUT: 900` (https://github.com/uc-cdis/fence/pull/1040)
- portal
  - New portal config options to exclude File nodes from the charts added: use `"graphql.chartNodesExcludeFiles"` to exclude File nodes from graphql chart, or use `"components.index.homepageChartNodesExcludeFiles"` to exclude File nodes from homepage chart. Note both of them are default to `false` so you have to explicitly set them to `true` to enable them (https://github.com/uc-cdis/data-portal/pull/1208)
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)
- sheepdog
  - Sheepdog does not rely on configuration files in the cloud-automation repository anymore. The Sheepdog configuration files are in the Sheepdog repository. (https://github.com/uc-cdis/sheepdog/pull/387)
## Breaking changes
- arborist
  - The `GET /auth/mapping` endpoint does not accept `username` as a query parameter anymore. It only supports parsing the username from the provided JWT. To specify a username, use the `POST /auth/mapping` endpoint. (https://github.com/uc-cdis/arborist/pull/153)
- fence
  - Default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP (https://github.com/uc-cdis/fence/pull/1040)
- indexd
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (https://github.com/uc-cdis/indexd/pull/338)
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (https://github.com/uc-cdis/indexd/pull/336)

**Comment by PlanXCyborg** [comment]
# chorus.data-commons.org
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [node_id] in explorerConfig.charts not found in etlMapping

**Comment by PlanXCyborg** [comment]
# chorus.data-commons.org/manifest.json
## Deployment changes
- dashboard
  - This change will add some CSP and CORS related header to the response that returned from the dashboard services. They should not be interruptive, but each team is encouraged to double check their webpages hosted by dashboard to ensure they still works (https://github.com/uc-cdis/gen3-statics/pull/27)
  - Because of these CSP directives being added, starting from this version, if anyone what to load remote scripts in their dashboard-hosted webpages, they will need to update the CSP directives in this dashboard service if the current directives doesn't fit, or to ship the script files with the page (https://github.com/uc-cdis/gen3-statics/pull/27)
- fence
  - Requires a Fence DB migration (https://github.com/uc-cdis/fence/pull/1068)
  - Configure the `ALLOWED_DATA_UPLOAD_BUCKETS` setting to allow users to upload to buckets other than `DATA_UPLOAD_BUCKET` (https://github.com/uc-cdis/fence/pull/1051)
  - B/c the default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP, you MUST ensure that an instance that should comply with FedRAMP does NOT override this fence configuration (e.g. it should be 15 minutes) `SESSION_TIMEOUT: 900` (https://github.com/uc-cdis/fence/pull/1040)
- portal
  - New portal config options to exclude File nodes from the charts added: use `"graphql.chartNodesExcludeFiles"` to exclude File nodes from graphql chart, or use `"components.index.homepageChartNodesExcludeFiles"` to exclude File nodes from homepage chart. Note both of them are default to `false` so you have to explicitly set them to `true` to enable them (https://github.com/uc-cdis/data-portal/pull/1208)
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)
- sheepdog
  - Sheepdog does not rely on configuration files in the cloud-automation repository anymore. The Sheepdog configuration files are in the Sheepdog repository. (https://github.com/uc-cdis/sheepdog/pull/387)
## Breaking changes
- arborist
  - The `GET /auth/mapping` endpoint does not accept `username` as a query parameter anymore. It only supports parsing the username from the provided JWT. To specify a username, use the `POST /auth/mapping` endpoint. (https://github.com/uc-cdis/arborist/pull/153)
- fence
  - Default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP (https://github.com/uc-cdis/fence/pull/1040)
- indexd
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (https://github.com/uc-cdis/indexd/pull/338)
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (https://github.com/uc-cdis/indexd/pull/336)

**Comment by PlanXCyborg** [comment]
# chorus.data-commons.org
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [node_id] in explorerConfig.charts not found in etlMapping

**Comment by PlanXCyborg** [comment]
# chorus.data-commons.org
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [node_id] in explorerConfig.charts not found in etlMapping

**Comment by PlanXCyborg** [comment]
# chorus.data-commons.org
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [node_id] in explorerConfig.charts not found in etlMapping

**Comment by PlanXCyborg** [comment]
# chorus.data-commons.org/manifest.json
## Deployment changes
- dashboard
  - This change will add some CSP and CORS related header to the response that returned from the dashboard services. They should not be interruptive, but each team is encouraged to double check their webpages hosted by dashboard to ensure they still works (https://github.com/uc-cdis/gen3-statics/pull/27)
  - Because of these CSP directives being added, starting from this version, if anyone what to load remote scripts in their dashboard-hosted webpages, they will need to update the CSP directives in this dashboard service if the current directives doesn't fit, or to ship the script files with the page (https://github.com/uc-cdis/gen3-statics/pull/27)
- fence
  - Requires a Fence DB migration (https://github.com/uc-cdis/fence/pull/1068)
  - Configure the `ALLOWED_DATA_UPLOAD_BUCKETS` setting to allow users to upload to buckets other than `DATA_UPLOAD_BUCKET` (https://github.com/uc-cdis/fence/pull/1051)
  - B/c the default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP, you MUST ensure that an instance that should comply with FedRAMP does NOT override this fence configuration (e.g. it should be 15 minutes) `SESSION_TIMEOUT: 900` (https://github.com/uc-cdis/fence/pull/1040)
- portal
  - New portal config options to exclude File nodes from the charts added: use `"graphql.chartNodesExcludeFiles"` to exclude File nodes from graphql chart, or use `"components.index.homepageChartNodesExcludeFiles"` to exclude File nodes from homepage chart. Note both of them are default to `false` so you have to explicitly set them to `true` to enable them (https://github.com/uc-cdis/data-portal/pull/1208)
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)
- sheepdog
  - Sheepdog does not rely on configuration files in the cloud-automation repository anymore. The Sheepdog configuration files are in the Sheepdog repository. (https://github.com/uc-cdis/sheepdog/pull/387)
## Breaking changes
- arborist
  - The `GET /auth/mapping` endpoint does not accept `username` as a query parameter anymore. It only supports parsing the username from the provided JWT. To specify a username, use the `POST /auth/mapping` endpoint. (https://github.com/uc-cdis/arborist/pull/153)
- fence
  - Default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP (https://github.com/uc-cdis/fence/pull/1040)
- indexd
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (https://github.com/uc-cdis/indexd/pull/338)
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (https://github.com/uc-cdis/indexd/pull/336)

**Comment by PlanXCyborg** [comment]
# chorus.data-commons.org
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [node_id] in explorerConfig.charts not found in etlMapping

**Comment by PlanXCyborg** [comment]
# chorus.data-commons.org/manifest.json
## Deployment changes
- dashboard
  - This change will add some CSP and CORS related header to the response that returned from the dashboard services. They should not be interruptive, but each team is encouraged to double check their webpages hosted by dashboard to ensure they still works (https://github.com/uc-cdis/gen3-statics/pull/27)
  - Because of these CSP directives being added, starting from this version, if anyone what to load remote scripts in their dashboard-hosted webpages, they will need to update the CSP directives in this dashboard service if the current directives doesn't fit, or to ship the script files with the page (https://github.com/uc-cdis/gen3-statics/pull/27)
- fence
  - Requires a Fence DB migration (https://github.com/uc-cdis/fence/pull/1068)
  - Configure the `ALLOWED_DATA_UPLOAD_BUCKETS` setting to allow users to upload to buckets other than `DATA_UPLOAD_BUCKET` (https://github.com/uc-cdis/fence/pull/1051)
  - B/c the default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP, you MUST ensure that an instance that should comply with FedRAMP does NOT override this fence configuration (e.g. it should be 15 minutes) `SESSION_TIMEOUT: 900` (https://github.com/uc-cdis/fence/pull/1040)
- portal
  - New portal config options to exclude File nodes from the charts added: use `"graphql.chartNodesExcludeFiles"` to exclude File nodes from graphql chart, or use `"components.index.homepageChartNodesExcludeFiles"` to exclude File nodes from homepage chart. Note both of them are default to `false` so you have to explicitly set them to `true` to enable them (https://github.com/uc-cdis/data-portal/pull/1208)
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)
- sheepdog
  - Sheepdog does not rely on configuration files in the cloud-automation repository anymore. The Sheepdog configuration files are in the Sheepdog repository. (https://github.com/uc-cdis/sheepdog/pull/387)
## Breaking changes
- arborist
  - The `GET /auth/mapping` endpoint does not accept `username` as a query parameter anymore. It only supports parsing the username from the provided JWT. To specify a username, use the `POST /auth/mapping` endpoint. (https://github.com/uc-cdis/arborist/pull/153)
- fence
  - Default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP (https://github.com/uc-cdis/fence/pull/1040)
- indexd
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (https://github.com/uc-cdis/indexd/pull/338)
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (https://github.com/uc-cdis/indexd/pull/336)

**Pull request merged**
