### PR TITLE
deploy heal filter update to preprod

### PR DESCRIPTION
**Pull request by mfshao**
Link to Jira ticket if there is one:

### Environments
- HEAL preprod

### Description of changes
- deploy filter changes

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# preprod.healdata.org/manifest.json
## Deployment changes
- portal
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)

**Review by MichaelLukowski — DISMISSED** [review]

**Comment by PlanXCyborg** [comment]
# preprod.healdata.org/manifest.json
## Deployment changes
- portal
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)

**Comment by PlanXCyborg** [comment]
# preprod.healdata.org/manifest.json
## Deployment changes
- portal
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)

**Comment by mfshao** [comment]
force merging this since we know the ci failures are false positives

**Pull request merged**
