### PR TITLE
Updating auspice version in COVID19 PROD

### PR DESCRIPTION
**Pull request by atharvar28**
updating the auspice version from `gen3-auspice:v2.16.gen3.3` to `gen3-auspice:v2.16.gen3.4`

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# chicagoland.pandemicresponsecommons.org/manifest.json
## :warning: Services on branch
- auspice

**Review by gkuffel — COMMENTED** [review]
portal version needs to be updated too.

**Review by gkuffel — APPROVED** [review]

**Comment by PlanXCyborg** [comment]
# chicagoland.pandemicresponsecommons.org/manifest.json
## :warning: Services on branch
- auspice

**Comment by PlanXCyborg** [comment]
# chicagoland.pandemicresponsecommons.org/manifest.json
## :warning: Services on branch
- auspice

**Pull request merged**
