### PR TITLE
chore/update_covid19-portal: update covid19 data-portal image to 3.3.0

### PR DESCRIPTION
**Pull request by ocshawn**
### Environments
PRC

## Bug Fixes
  - Fix broken carousel styling introduced in release 3.0.0 (#895)

## New Features
  - Create Date slider on maps to view data changes over time (#875)
  - Create multiple map layers to view other data (#875)
  - remove unneeded css

### CODE REVIEW

**Review by paulineribeyre — APPROVED** [review]
pending PM approval

**Review by atharvar28 — APPROVED** [review]
Lgtm 👍

**Review by paulineribeyre — CHANGES_REQUESTED** [review]
not ready to merge

**Review by paulineribeyre — APPROVED** [review]
ready to merge :p

**Pull request merged**
