### PR TITLE
Gen3 Monthly Release 2023.02 caninedc.org 1674848031

### PR DESCRIPTION
**Pull request by PlanXCyborg**
Applying version 2023.02 to caninedc.org

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# caninedc.org
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [node_id] in explorerConfig.charts not found in etlMapping

**Comment by PlanXCyborg** [comment]
# caninedc.org/manifest.json
## Deployment changes
- fence
  - Requires a Fence DB migration (https://github.com/uc-cdis/fence/pull/1068)
  - [PXP-10541]: https://ctds-planx.atlassian.net/browse/PXP-10541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ (https://github.com/uc-cdis/fence/pull/1068)
- portal
  - New portal config options to exclude File nodes from the charts added: use `"graphql.chartNodesExcludeFiles"` to exclude File nodes from graphql chart, or use `"components.index.homepageChartNodesExcludeFiles"` to exclude File nodes from homepage chart. Note both of them are default to `false` so you have to explicitly set them to `true` to enable them (https://github.com/uc-cdis/data-portal/pull/1208)
  - [PXP-10565]: https://ctds-planx.atlassian.net/browse/PXP-10565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ (https://github.com/uc-cdis/data-portal/pull/1208)
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)
- sower
  - [PPS-169]: https://ctds-planx.atlassian.net/browse/PPS-169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ (https://github.com/uc-cdis/sower/pull/36)
- ssjdispatcher
  - [PPS-169]: https://ctds-planx.atlassian.net/browse/PPS-169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ (https://github.com/uc-cdis/ssjdispatcher/pull/46)
- tube
  - [PXP-10516]: https://ctds-planx.atlassian.net/browse/PXP-10516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ (https://github.com/uc-cdis/tube/pull/220)
## Breaking changes
- indexd
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (https://github.com/uc-cdis/indexd/pull/338)

**Review by trevars — APPROVED** [review]

**Comment by PlanXCyborg** [comment]
# caninedc.org
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [node_id] in explorerConfig.charts not found in etlMapping

**Comment by PlanXCyborg** [comment]
# caninedc.org/manifest.json
## Deployment changes
- fence
  - Requires a Fence DB migration (https://github.com/uc-cdis/fence/pull/1068)
  - [PXP-10541]: https://ctds-planx.atlassian.net/browse/PXP-10541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ (https://github.com/uc-cdis/fence/pull/1068)
- portal
  - New portal config options to exclude File nodes from the charts added: use `"graphql.chartNodesExcludeFiles"` to exclude File nodes from graphql chart, or use `"components.index.homepageChartNodesExcludeFiles"` to exclude File nodes from homepage chart. Note both of them are default to `false` so you have to explicitly set them to `true` to enable them (https://github.com/uc-cdis/data-portal/pull/1208)
  - [PXP-10565]: https://ctds-planx.atlassian.net/browse/PXP-10565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ (https://github.com/uc-cdis/data-portal/pull/1208)
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)
- sower
  - [PPS-169]: https://ctds-planx.atlassian.net/browse/PPS-169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ (https://github.com/uc-cdis/sower/pull/36)
- ssjdispatcher
  - [PPS-169]: https://ctds-planx.atlassian.net/browse/PPS-169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ (https://github.com/uc-cdis/ssjdispatcher/pull/46)
- tube
  - [PXP-10516]: https://ctds-planx.atlassian.net/browse/PXP-10516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ (https://github.com/uc-cdis/tube/pull/220)
## Breaking changes
- indexd
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (https://github.com/uc-cdis/indexd/pull/338)

**Pull request closed without merging**
