### PR TITLE
deploy vlmd sub to preprod heal

### PR DESCRIPTION
**Pull request by mfshao**
Link to Jira ticket if there is one:

### Environments
- HEAL Preprod

### Description of changes
- deploy vlmd submission page

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# preprod.healdata.org/manifest.json
## :warning: Services are being downgraded
- portal

**Comment by PlanXCyborg** [comment]
# preprod.healdata.org/manifest.json
## :warning: Services are being downgraded
- portal

**Review by hughestr — APPROVED** [review]

**Comment by PlanXCyborg** [comment]
# preprod.healdata.org/manifest.json
## :warning: Services are being downgraded
- portal

**Comment by mfshao** [comment]
discovery page has a known issue at this time and its failure is not caused by this PR, merging for now

**Comment by PlanXCyborg** [comment]
# preprod.healdata.org/manifest.json
## :warning: Services are being downgraded
- portal

**Pull request merged**
