### PR TITLE
Gen3 Monthly Release 2022.10 icgc.bionimbus.org 1666302716

### PR DESCRIPTION
**Pull request by PlanXCyborg**
Applying version 2022.10 to icgc.bionimbus.org

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# icgc.bionimbus.org/manifest.json
## Deployment changes
- arborist
  - Replace Travis with a GitHub workflow for CI (uc-cdis/arborist#150)
- fence
  - Configure the `ALLOWED_DATA_UPLOAD_BUCKETS` setting to allow users to upload to buckets other than `DATA_UPLOAD_BUCKET` (uc-cdis/fence#1051)
  - B/c the default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP, you MUST ensure that an instance that should comply with FedRAMP does NOT override this fence configuration (e.g. it should be 15 minutes) `SESSION_TIMEOUT: 900` (uc-cdis/fence#1040)
  - Requires a Fence DB migration (`Client.redirect_uri` is now optional) (uc-cdis/fence#1033)
  - Requires database migration for a new table to Fence, google Access expiration to add new `expires` column, and to create iss_sub_pair_to_user table #968  #963  #973 (uc-cdis/fence#964)
  - Requires Arborist >= `2022.04` OR >=`3.4.0` https://github.com/uc-cdis/arborist/pull/143 (uc-cdis/fence#964)
  - To enable Passports -> DRS in an environment you must update Fence Configuration to at a minimum specify `GA4GH_PASSPORTS_TO_DRS_ENABLED: true` (**only do this after coordinating with the environment owner as this has several requirements before it can be enabled, including the need to use Indexd's `authz` field in ALL records rather than `acl`**) (uc-cdis/fence#964)
- portal
  - Added new optional field `stridesPortalURL` in portal config which can display a link to the STRIDES admin portal on workspace page (uc-cdis/data-portal#978)
  - For decoupled workspace, must work with Hatchery `1.0.0+` (uc-cdis/data-portal#978)
  - See gitops configuration options for tabbed metadata detail vs traditional (uc-cdis/data-portal#983)
## Breaking changes
- arborist
  - The `GET /auth/mapping` endpoint does not accept `username` as a query parameter anymore. It only supports parsing the username from the provided JWT. To specify a username, use the `POST /auth/mapping` endpoint. (uc-cdis/arborist#153)
- fence
  - Default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP (uc-cdis/fence#1040)
  - URL Signing when no_force_sign query param is provided: Previously Fence would make a decision based off if the data was public and no_force_sign provided. Fence will now NEVER sign if no_force_sign is provided (since the concept of "public" data has been abstracted out of Fence. Data access - public or not - is the sole responsibility of the policy engine). In other words, if no_force_sign is provided at the API level, Fence will respect that regardless of whether the resulting URL will actually work. The default Fence behavior should remain the same. #988 (uc-cdis/fence#964)
- indexd
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (uc-cdis/indexd#336)
- portal
  - Replaced loading  the data in  `iframes` in Workspace page with Redirect component. (uc-cdis/data-portal#1067)
  - Deprecating the use of `default-workspaces` i. e an individual commons will no longer be able to deploy standalone jupyterhub images, they may use [hatchery service](https://github.com/uc-cdis/hatchery) instead. (uc-cdis/data-portal#1067)
  - `studyRegistrationConfig` in `gitops.json` must now be placed within the `regsitrationConfigs.features` block [[Refer this PR](https://github.com/uc-cdis/cdis-manifest/pull/5095)] (uc-cdis/data-portal#1067)

**Review by trevars — APPROVED** [review]

**Comment by PlanXCyborg** [comment]
# icgc.bionimbus.org/manifest.json
## Deployment changes
- arborist
  - Replace Travis with a GitHub workflow for CI (uc-cdis/arborist#150)
- fence
  - Configure the `ALLOWED_DATA_UPLOAD_BUCKETS` setting to allow users to upload to buckets other than `DATA_UPLOAD_BUCKET` (uc-cdis/fence#1051)
  - B/c the default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP, you MUST ensure that an instance that should comply with FedRAMP does NOT override this fence configuration (e.g. it should be 15 minutes) `SESSION_TIMEOUT: 900` (uc-cdis/fence#1040)
  - Requires a Fence DB migration (`Client.redirect_uri` is now optional) (uc-cdis/fence#1033)
  - Requires database migration for a new table to Fence, google Access expiration to add new `expires` column, and to create iss_sub_pair_to_user table #968  #963  #973 (uc-cdis/fence#964)
  - Requires Arborist >= `2022.04` OR >=`3.4.0` https://github.com/uc-cdis/arborist/pull/143 (uc-cdis/fence#964)
  - To enable Passports -> DRS in an environment you must update Fence Configuration to at a minimum specify `GA4GH_PASSPORTS_TO_DRS_ENABLED: true` (**only do this after coordinating with the environment owner as this has several requirements before it can be enabled, including the need to use Indexd's `authz` field in ALL records rather than `acl`**) (uc-cdis/fence#964)
- portal
  - Added new optional field `stridesPortalURL` in portal config which can display a link to the STRIDES admin portal on workspace page (uc-cdis/data-portal#978)
  - For decoupled workspace, must work with Hatchery `1.0.0+` (uc-cdis/data-portal#978)
  - See gitops configuration options for tabbed metadata detail vs traditional (uc-cdis/data-portal#983)
## Breaking changes
- arborist
  - The `GET /auth/mapping` endpoint does not accept `username` as a query parameter anymore. It only supports parsing the username from the provided JWT. To specify a username, use the `POST /auth/mapping` endpoint. (uc-cdis/arborist#153)
- fence
  - Default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP (uc-cdis/fence#1040)
  - URL Signing when no_force_sign query param is provided: Previously Fence would make a decision based off if the data was public and no_force_sign provided. Fence will now NEVER sign if no_force_sign is provided (since the concept of "public" data has been abstracted out of Fence. Data access - public or not - is the sole responsibility of the policy engine). In other words, if no_force_sign is provided at the API level, Fence will respect that regardless of whether the resulting URL will actually work. The default Fence behavior should remain the same. #988 (uc-cdis/fence#964)
- indexd
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (uc-cdis/indexd#336)
- portal
  - Replaced loading  the data in  `iframes` in Workspace page with Redirect component. (uc-cdis/data-portal#1067)
  - Deprecating the use of `default-workspaces` i. e an individual commons will no longer be able to deploy standalone jupyterhub images, they may use [hatchery service](https://github.com/uc-cdis/hatchery) instead. (uc-cdis/data-portal#1067)
  - `studyRegistrationConfig` in `gitops.json` must now be placed within the `regsitrationConfigs.features` block [[Refer this PR](https://github.com/uc-cdis/cdis-manifest/pull/5095)] (uc-cdis/data-portal#1067)

**Comment by PlanXCyborg** [comment]
# icgc.bionimbus.org/manifest.json
## Deployment changes
- arborist
  - Replace Travis with a GitHub workflow for CI (uc-cdis/arborist#150)
- fence
  - Configure the `ALLOWED_DATA_UPLOAD_BUCKETS` setting to allow users to upload to buckets other than `DATA_UPLOAD_BUCKET` (uc-cdis/fence#1051)
  - B/c the default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP, you MUST ensure that an instance that should comply with FedRAMP does NOT override this fence configuration (e.g. it should be 15 minutes) `SESSION_TIMEOUT: 900` (uc-cdis/fence#1040)
  - Requires a Fence DB migration (`Client.redirect_uri` is now optional) (uc-cdis/fence#1033)
  - Requires database migration for a new table to Fence, google Access expiration to add new `expires` column, and to create iss_sub_pair_to_user table #968  #963  #973 (uc-cdis/fence#964)
  - Requires Arborist >= `2022.04` OR >=`3.4.0` https://github.com/uc-cdis/arborist/pull/143 (uc-cdis/fence#964)
  - To enable Passports -> DRS in an environment you must update Fence Configuration to at a minimum specify `GA4GH_PASSPORTS_TO_DRS_ENABLED: true` (**only do this after coordinating with the environment owner as this has several requirements before it can be enabled, including the need to use Indexd's `authz` field in ALL records rather than `acl`**) (uc-cdis/fence#964)
- portal
  - Added new optional field `stridesPortalURL` in portal config which can display a link to the STRIDES admin portal on workspace page (uc-cdis/data-portal#978)
  - For decoupled workspace, must work with Hatchery `1.0.0+` (uc-cdis/data-portal#978)
  - See gitops configuration options for tabbed metadata detail vs traditional (uc-cdis/data-portal#983)
## Breaking changes
- arborist
  - The `GET /auth/mapping` endpoint does not accept `username` as a query parameter anymore. It only supports parsing the username from the provided JWT. To specify a username, use the `POST /auth/mapping` endpoint. (uc-cdis/arborist#153)
- fence
  - Default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP (uc-cdis/fence#1040)
  - URL Signing when no_force_sign query param is provided: Previously Fence would make a decision based off if the data was public and no_force_sign provided. Fence will now NEVER sign if no_force_sign is provided (since the concept of "public" data has been abstracted out of Fence. Data access - public or not - is the sole responsibility of the policy engine). In other words, if no_force_sign is provided at the API level, Fence will respect that regardless of whether the resulting URL will actually work. The default Fence behavior should remain the same. #988 (uc-cdis/fence#964)
- indexd
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (uc-cdis/indexd#336)
- portal
  - Replaced loading  the data in  `iframes` in Workspace page with Redirect component. (uc-cdis/data-portal#1067)
  - Deprecating the use of `default-workspaces` i. e an individual commons will no longer be able to deploy standalone jupyterhub images, they may use [hatchery service](https://github.com/uc-cdis/hatchery) instead. (uc-cdis/data-portal#1067)
  - `studyRegistrationConfig` in `gitops.json` must now be placed within the `regsitrationConfigs.features` block [[Refer this PR](https://github.com/uc-cdis/cdis-manifest/pull/5095)] (uc-cdis/data-portal#1067)

**Comment by PlanXCyborg** [comment]
# icgc.bionimbus.org/manifest.json
## Deployment changes
- arborist
  - Replace Travis with a GitHub workflow for CI (uc-cdis/arborist#150)
- fence
  - Configure the `ALLOWED_DATA_UPLOAD_BUCKETS` setting to allow users to upload to buckets other than `DATA_UPLOAD_BUCKET` (uc-cdis/fence#1051)
  - B/c the default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP, you MUST ensure that an instance that should comply with FedRAMP does NOT override this fence configuration (e.g. it should be 15 minutes) `SESSION_TIMEOUT: 900` (uc-cdis/fence#1040)
  - Requires a Fence DB migration (`Client.redirect_uri` is now optional) (uc-cdis/fence#1033)
  - Requires database migration for a new table to Fence, google Access expiration to add new `expires` column, and to create iss_sub_pair_to_user table #968  #963  #973 (uc-cdis/fence#964)
  - Requires Arborist >= `2022.04` OR >=`3.4.0` https://github.com/uc-cdis/arborist/pull/143 (uc-cdis/fence#964)
  - To enable Passports -> DRS in an environment you must update Fence Configuration to at a minimum specify `GA4GH_PASSPORTS_TO_DRS_ENABLED: true` (**only do this after coordinating with the environment owner as this has several requirements before it can be enabled, including the need to use Indexd's `authz` field in ALL records rather than `acl`**) (uc-cdis/fence#964)
- portal
  - Added new optional field `stridesPortalURL` in portal config which can display a link to the STRIDES admin portal on workspace page (uc-cdis/data-portal#978)
  - For decoupled workspace, must work with Hatchery `1.0.0+` (uc-cdis/data-portal#978)
  - See gitops configuration options for tabbed metadata detail vs traditional (uc-cdis/data-portal#983)
## Breaking changes
- arborist
  - The `GET /auth/mapping` endpoint does not accept `username` as a query parameter anymore. It only supports parsing the username from the provided JWT. To specify a username, use the `POST /auth/mapping` endpoint. (uc-cdis/arborist#153)
- fence
  - Default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP (uc-cdis/fence#1040)
  - URL Signing when no_force_sign query param is provided: Previously Fence would make a decision based off if the data was public and no_force_sign provided. Fence will now NEVER sign if no_force_sign is provided (since the concept of "public" data has been abstracted out of Fence. Data access - public or not - is the sole responsibility of the policy engine). In other words, if no_force_sign is provided at the API level, Fence will respect that regardless of whether the resulting URL will actually work. The default Fence behavior should remain the same. #988 (uc-cdis/fence#964)
- indexd
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (uc-cdis/indexd#336)
- portal
  - Replaced loading  the data in  `iframes` in Workspace page with Redirect component. (uc-cdis/data-portal#1067)
  - Deprecating the use of `default-workspaces` i. e an individual commons will no longer be able to deploy standalone jupyterhub images, they may use [hatchery service](https://github.com/uc-cdis/hatchery) instead. (uc-cdis/data-portal#1067)
  - `studyRegistrationConfig` in `gitops.json` must now be placed within the `regsitrationConfigs.features` block [[Refer this PR](https://github.com/uc-cdis/cdis-manifest/pull/5095)] (uc-cdis/data-portal#1067)

**Comment by PlanXCyborg** [comment]
# icgc.bionimbus.org/manifest.json
## Deployment changes
- arborist
  - Replace Travis with a GitHub workflow for CI (uc-cdis/arborist#150)
- fence
  - Configure the `ALLOWED_DATA_UPLOAD_BUCKETS` setting to allow users to upload to buckets other than `DATA_UPLOAD_BUCKET` (uc-cdis/fence#1051)
  - B/c the default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP, you MUST ensure that an instance that should comply with FedRAMP does NOT override this fence configuration (e.g. it should be 15 minutes) `SESSION_TIMEOUT: 900` (uc-cdis/fence#1040)
  - Requires a Fence DB migration (`Client.redirect_uri` is now optional) (uc-cdis/fence#1033)
  - Requires database migration for a new table to Fence, google Access expiration to add new `expires` column, and to create iss_sub_pair_to_user table #968  #963  #973 (uc-cdis/fence#964)
  - Requires Arborist >= `2022.04` OR >=`3.4.0` https://github.com/uc-cdis/arborist/pull/143 (uc-cdis/fence#964)
  - To enable Passports -> DRS in an environment you must update Fence Configuration to at a minimum specify `GA4GH_PASSPORTS_TO_DRS_ENABLED: true` (**only do this after coordinating with the environment owner as this has several requirements before it can be enabled, including the need to use Indexd's `authz` field in ALL records rather than `acl`**) (uc-cdis/fence#964)
- portal
  - Added new optional field `stridesPortalURL` in portal config which can display a link to the STRIDES admin portal on workspace page (uc-cdis/data-portal#978)
  - For decoupled workspace, must work with Hatchery `1.0.0+` (uc-cdis/data-portal#978)
  - See gitops configuration options for tabbed metadata detail vs traditional (uc-cdis/data-portal#983)
## Breaking changes
- arborist
  - The `GET /auth/mapping` endpoint does not accept `username` as a query parameter anymore. It only supports parsing the username from the provided JWT. To specify a username, use the `POST /auth/mapping` endpoint. (uc-cdis/arborist#153)
- fence
  - Default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP (uc-cdis/fence#1040)
  - URL Signing when no_force_sign query param is provided: Previously Fence would make a decision based off if the data was public and no_force_sign provided. Fence will now NEVER sign if no_force_sign is provided (since the concept of "public" data has been abstracted out of Fence. Data access - public or not - is the sole responsibility of the policy engine). In other words, if no_force_sign is provided at the API level, Fence will respect that regardless of whether the resulting URL will actually work. The default Fence behavior should remain the same. #988 (uc-cdis/fence#964)
- indexd
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (uc-cdis/indexd#336)
- portal
  - Replaced loading  the data in  `iframes` in Workspace page with Redirect component. (uc-cdis/data-portal#1067)
  - Deprecating the use of `default-workspaces` i. e an individual commons will no longer be able to deploy standalone jupyterhub images, they may use [hatchery service](https://github.com/uc-cdis/hatchery) instead. (uc-cdis/data-portal#1067)
  - `studyRegistrationConfig` in `gitops.json` must now be placed within the `regsitrationConfigs.features` block [[Refer this PR](https://github.com/uc-cdis/cdis-manifest/pull/5095)] (uc-cdis/data-portal#1067)

**Comment by PlanXCyborg** [comment]
# icgc.bionimbus.org/manifest.json
## Deployment changes
- arborist
  - Replace Travis with a GitHub workflow for CI (uc-cdis/arborist#150)
- fence
  - Configure the `ALLOWED_DATA_UPLOAD_BUCKETS` setting to allow users to upload to buckets other than `DATA_UPLOAD_BUCKET` (uc-cdis/fence#1051)
  - B/c the default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP, you MUST ensure that an instance that should comply with FedRAMP does NOT override this fence configuration (e.g. it should be 15 minutes) `SESSION_TIMEOUT: 900` (uc-cdis/fence#1040)
  - Requires a Fence DB migration (`Client.redirect_uri` is now optional) (uc-cdis/fence#1033)
  - Requires database migration for a new table to Fence, google Access expiration to add new `expires` column, and to create iss_sub_pair_to_user table #968  #963  #973 (uc-cdis/fence#964)
  - Requires Arborist >= `2022.04` OR >=`3.4.0` https://github.com/uc-cdis/arborist/pull/143 (uc-cdis/fence#964)
  - To enable Passports -> DRS in an environment you must update Fence Configuration to at a minimum specify `GA4GH_PASSPORTS_TO_DRS_ENABLED: true` (**only do this after coordinating with the environment owner as this has several requirements before it can be enabled, including the need to use Indexd's `authz` field in ALL records rather than `acl`**) (uc-cdis/fence#964)
- portal
  - Added new optional field `stridesPortalURL` in portal config which can display a link to the STRIDES admin portal on workspace page (uc-cdis/data-portal#978)
  - For decoupled workspace, must work with Hatchery `1.0.0+` (uc-cdis/data-portal#978)
  - See gitops configuration options for tabbed metadata detail vs traditional (uc-cdis/data-portal#983)
## Breaking changes
- arborist
  - The `GET /auth/mapping` endpoint does not accept `username` as a query parameter anymore. It only supports parsing the username from the provided JWT. To specify a username, use the `POST /auth/mapping` endpoint. (uc-cdis/arborist#153)
- fence
  - Default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP (uc-cdis/fence#1040)
  - URL Signing when no_force_sign query param is provided: Previously Fence would make a decision based off if the data was public and no_force_sign provided. Fence will now NEVER sign if no_force_sign is provided (since the concept of "public" data has been abstracted out of Fence. Data access - public or not - is the sole responsibility of the policy engine). In other words, if no_force_sign is provided at the API level, Fence will respect that regardless of whether the resulting URL will actually work. The default Fence behavior should remain the same. #988 (uc-cdis/fence#964)
- indexd
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (uc-cdis/indexd#336)
- portal
  - Replaced loading  the data in  `iframes` in Workspace page with Redirect component. (uc-cdis/data-portal#1067)
  - Deprecating the use of `default-workspaces` i. e an individual commons will no longer be able to deploy standalone jupyterhub images, they may use [hatchery service](https://github.com/uc-cdis/hatchery) instead. (uc-cdis/data-portal#1067)
  - `studyRegistrationConfig` in `gitops.json` must now be placed within the `regsitrationConfigs.features` block [[Refer this PR](https://github.com/uc-cdis/cdis-manifest/pull/5095)] (uc-cdis/data-portal#1067)

**Review by trevars — APPROVED** [review]

**Pull request merged**
