### PR TITLE
Gen3 Monthly Release 2020.05 internalstaging.theanvil.io 1588787834

### PR DESCRIPTION
**Pull request by themarcelor**
Applying version 2020.05 to internalstaging.theanvil.io

### CODE REVIEW

**Comment by paulineribeyre** [comment]
# internalstaging.theanvil.io/manifest.json
## Deployment changes
- fence
  - To use the new Cognito integration, apply in fence config the changes made to config-default.yaml. Otherwise no action required. (uc-cdis/fence#767)
- portal
  - The Terra template attribute in gitops.json now expects a list of strings, not just a single string. (uc-cdis/portal#663)

**Comment by paulineribeyre** [comment]
# internalstaging.theanvil.io/manifest.json
## Deployment changes
- fence
  - To use the new Cognito integration, apply in fence config the changes made to config-default.yaml. Otherwise no action required. (uc-cdis/fence#767)
- portal
  - The Terra template attribute in gitops.json now expects a list of strings, not just a single string. (uc-cdis/portal#663)

**Comment by paulineribeyre** [comment]
# internalstaging.theanvil.io/manifest.json
## Deployment changes
- fence
  - To use the new Cognito integration, apply in fence config the changes made to config-default.yaml. Otherwise no action required. (uc-cdis/fence#767)
- portal
  - The Terra template attribute in gitops.json now expects a list of strings, not just a single string. (uc-cdis/portal#663)

**Comment by PlanXCyborg** [comment]
# internalstaging.theanvil.io/manifest.json
## Deployment changes
- fence
  - To use the new Cognito integration, apply in fence config the changes made to config-default.yaml. Otherwise no action required. (uc-cdis/fence#767)
- portal
  - The Terra template attribute in gitops.json now expects a list of strings, not just a single string. (uc-cdis/portal#663)

**Pull request merged**
