### PR TITLE
Setup Explorer

### PR DESCRIPTION
**Pull request by FayBooker2**
(https://ctds-planx.atlassian.net/browse/ELW-7)
### Environments
eLwazi Demo Commons

### Description of changes
Update ETL Mapping file and gitops.json to support exploration operations

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# elwazi-demo.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [_subject_id] in explorerConfig.charts not found in etlMapping
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# elwazi-demo.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [_subject_id] in explorerConfig.charts not found in etlMapping
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# elwazi-demo.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# elwazi-demo.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping

**Review by cgmeyer — DISMISSED** [review]
looks good to me; only comment is you may want to consider reformatting into a single "explorerConfig" block instead of using "dataExplorerConfig" and "fileExplorerConfig".

For example, like in PRC:
[https://github.com/uc-cdis/cdis-manifest/blob/d8a766c8a4ecf9433e2f267a22d25a388ba4[…]3a87/chicagoland.pandemicresponsecommons.org/portal/gitops.json](https://github.com/uc-cdis/cdis-manifest/blob/d8a766c8a4ecf9433e2f267a22d25a388ba43a87/chicagoland.pandemicresponsecommons.org/portal/gitops.json#L141)

**Pull request closed without merging**
