### PR TITLE
chore(metadata): migrate agg MDS configs

### PR DESCRIPTION
**Pull request by williamhaley**
Sibling PR to https://github.com/uc-cdis/cloud-automation/pull/1701 for [HP-291](https://ctds-planx.atlassian.net/browse/HP-291), [HP-320](https://ctds-planx.atlassian.net/browse/HP-320)

### Environments

* BRH Prod
* HEAL Preprod
* HEAL Prod

### Description of changes

* Migrate placeholder g3auto configs to manifest.json
* Migrate aggregate metadata configs from source code to respective manifest configs

### CODE REVIEW

**Comment by williamhaley** [comment]
This can be safely merged without impacting anything. Nothing here will be utilized until https://github.com/uc-cdis/cloud-automation/pull/1701 and related changes are merged

**Review by jawadqur — APPROVED** [review]

**Comment by PlanXCyborg** [comment]
# brh.data-commons.org/manifest.json
## :warning: Services on branch
- hatchery
- metadata
- portal
- revproxy
# healdata.org/manifest.json
## :warning: Services on branch
- hatchery
- metadata
- portal
# preprod.healdata.org/manifest.json
## :warning: Services on branch
- hatchery
- metadata
- portal

**Review by haraprasadj — APPROVED** [review]

**Review by jmontmaxwell — APPROVED** [review]

**Review by craigrbarnes — APPROVED** [review]

**Comment by PlanXCyborg** [comment]
# brh.data-commons.org/manifest.json
## :warning: Services on branch
- hatchery
- metadata
- portal
- revproxy
# healdata.org/manifest.json
## :warning: Services on branch
- hatchery
- metadata
- portal
# preprod.healdata.org/manifest.json
## :warning: Services on branch
- hatchery
- metadata
- portal

**Comment by PlanXCyborg** [comment]
# brh.data-commons.org/manifest.json
## :warning: Services on branch
- hatchery
- metadata
- portal
- revproxy
# healdata.org/manifest.json
## :warning: Services on branch
- hatchery
- metadata
- portal
# preprod.healdata.org/manifest.json
## :warning: Services on branch
- hatchery
- metadata
- portal

**Comment by PlanXCyborg** [comment]
# brh.data-commons.org/manifest.json
## :warning: Services on branch
- hatchery
- metadata
- portal
- revproxy
# healdata.org/manifest.json
## :warning: Services on branch
- hatchery
- metadata
- portal
# preprod.healdata.org/manifest.json
## :warning: Services on branch
- hatchery
- metadata
- portal

**Comment by PlanXCyborg** [comment]
# brh.data-commons.org/manifest.json
## :warning: Services on branch
- hatchery
- metadata
- portal
- revproxy
# healdata.org/manifest.json
## :warning: Services on branch
- hatchery
- metadata
- portal
# preprod.healdata.org/manifest.json
## :warning: Services on branch
- hatchery
- metadata
- portal

**Comment by PlanXCyborg** [comment]
# brh.data-commons.org/manifest.json
## :warning: Services on branch
- hatchery
- metadata
- portal
- revproxy
# healdata.org/manifest.json
## :warning: Services on branch
- hatchery
- metadata
- portal
# preprod.healdata.org/manifest.json
## :warning: Services on branch
- hatchery
- metadata
- portal

**Comment by PlanXCyborg** [comment]
# preprod.healdata.org/manifest.json
## :warning: Services on branch
- hatchery
- metadata
- portal

**Comment by PlanXCyborg** [comment]
# preprod.healdata.org/manifest.json
## :warning: Services on branch
- hatchery
- metadata
- portal

**Comment by PlanXCyborg** [comment]
# preprod.healdata.org/manifest.json
## :warning: Services on branch
- hatchery
- metadata
- portal

**Comment by PlanXCyborg** [comment]
# preprod.healdata.org/manifest.json
## :warning: Services on branch
- hatchery
- metadata
- portal

**Comment by PlanXCyborg** [comment]
# preprod.healdata.org/manifest.json
## :warning: Services on branch
- hatchery
- metadata
- portal

**Pull request merged**
