### PR TITLE
Gen3 Monthly Release 2023.01 nci-crdc-staging.datacommons.io 1673478410

### PR DESCRIPTION
**Pull request by PlanXCyborg**
Applying version 2023.01 to nci-crdc-staging.datacommons.io

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# nci-crdc-staging.datacommons.io/manifest.json
## Deployment changes
- portal
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)
- sower
  - [PPS-169]: https://ctds-planx.atlassian.net/browse/PPS-169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ (https://github.com/uc-cdis/sower/pull/36)
- ssjdispatcher
  - [PPS-169]: https://ctds-planx.atlassian.net/browse/PPS-169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ (https://github.com/uc-cdis/ssjdispatcher/pull/46)
## Breaking changes
- indexd
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (https://github.com/uc-cdis/indexd/pull/338)

**Comment by PlanXCyborg** [comment]
# nci-crdc-staging.datacommons.io/manifest.json
## Deployment changes
- portal
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)
- sower
  - [PPS-169]: https://ctds-planx.atlassian.net/browse/PPS-169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ (https://github.com/uc-cdis/sower/pull/36)
- ssjdispatcher
  - [PPS-169]: https://ctds-planx.atlassian.net/browse/PPS-169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ (https://github.com/uc-cdis/ssjdispatcher/pull/46)
## Breaking changes
- indexd
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (https://github.com/uc-cdis/indexd/pull/338)

**Review by frankliuao — APPROVED** [review]
Release of `2023.01` from `2022.12`. No special changes. Approved.

**Comment by PlanXCyborg** [comment]
# nci-crdc-staging.datacommons.io/manifest.json
## Deployment changes
- dashboard
  - This change will add some CSP and CORS related header to the response that returned from the dashboard services. They should not be interruptive, but each team is encouraged to double check their webpages hosted by dashboard to ensure they still works (https://github.com/uc-cdis/gen3-statics/pull/27)
  - Because of these CSP directives being added, starting from this version, if anyone what to load remote scripts in their dashboard-hosted webpages, they will need to update the CSP directives in this dashboard service if the current directives doesn't fit, or to ship the script files with the page (https://github.com/uc-cdis/gen3-statics/pull/27)
  - [PPS-154]: https://ctds-planx.atlassian.net/browse/PPS-154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ (https://github.com/uc-cdis/gen3-statics/pull/27)
- portal
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)
- sower
  - [PPS-169]: https://ctds-planx.atlassian.net/browse/PPS-169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ (https://github.com/uc-cdis/sower/pull/36)
- ssjdispatcher
  - [PPS-169]: https://ctds-planx.atlassian.net/browse/PPS-169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ (https://github.com/uc-cdis/ssjdispatcher/pull/46)
## Breaking changes
- indexd
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (https://github.com/uc-cdis/indexd/pull/338)

**Comment by frankliuao** [comment]
2023.01 is being skipped. Cancelling the PR.

**Pull request closed without merging**
