### PR TITLE
feat(elwazi-demo): Added manifest for elwazi demo

### PR DESCRIPTION
**Pull request by emalinowski**
Link to Jira ticket if there is one:

### Environments
elwazi demo

### CODE REVIEW

**Review by cgmeyer — DISMISSED** [review]

**Comment by PlanXCyborg** [comment]
# elwazi-demo.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [_case_id] in explorerConfig.charts not found in etlMapping

**Comment by PlanXCyborg** [comment]
# elwazi-demo.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [_case_id] in explorerConfig.charts not found in etlMapping

**Comment by PlanXCyborg** [comment]
# elwazi-demo.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [_case_id] in explorerConfig.charts not found in etlMapping

**Review by cgmeyer — APPROVED** [review]
🍕 🍕

**Pull request merged**
