### PR TITLE
chore(nde-dns): Updated NDE dns name

### PR DESCRIPTION
**Pull request by emalinowski**
Link to Jira ticket if there is one:

### Environments
NDE envs

### Description of changes
Updated domain name

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# aids.diseasedatahub.org/manifest.json
## :warning: Services on branch
- revproxy
# diseasedatahub.org/manifest.json
## :warning: Services on branch
- revproxy
# flu.diseasedatahub.org/manifest.json
## :warning: Services on branch
- revproxy
# microbiome.diseasedatahub.org/manifest.json
## :warning: Services on branch
- manifestservice
- revproxy
- sower
- dashboard

**Review by trevars — DISMISSED** [review]
lgtm

**Comment by PlanXCyborg** [comment]
# aids.diseasedatahub.org/manifest.json
## :warning: Services on branch
- revproxy
# diseasedatahub.org/manifest.json
## :warning: Services on branch
- revproxy
# flu.diseasedatahub.org/manifest.json
## :warning: Services on branch
- revproxy
# microbiome.diseasedatahub.org/manifest.json
## :warning: Services on branch
- manifestservice
- revproxy
- sower
- dashboard

**Review by trevars — APPROVED** [review]
Lgtm

**Pull request merged**
