### PR TITLE
Chore/update brh metadata

### PR DESCRIPTION
**Pull request by craigrbarnes**
Link to Jira ticket if there is one:

### Description of changes
Changed manifest to use master for metadata service. 
Update config to remove GDC/KF __manifest data

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# brh.data-commons.org/manifest.json
## :warning: Services on branch
- hatchery
- metadata
- portal
- revproxy

**Comment by PlanXCyborg** [comment]
# brh.data-commons.org/manifest.json
## :warning: Services on branch
- hatchery
- metadata
- portal
- revproxy

**Comment by PlanXCyborg** [comment]
# brh.data-commons.org/manifest.json
## :warning: Services on branch
- hatchery
- portal
- revproxy

**Comment by PlanXCyborg** [comment]
# brh.data-commons.org/manifest.json
## :warning: Services on branch
- revproxy

**Comment by PlanXCyborg** [comment]
# brh.data-commons.org/manifest.json
## :warning: Services on branch
- revproxy

**Comment by PlanXCyborg** [comment]
# brh.data-commons.org/manifest.json
## :warning: Services on branch
- revproxy

**Comment by PlanXCyborg** [comment]
# brh.data-commons.org/manifest.json
## :warning: Services on branch
- revproxy

**Comment by PlanXCyborg** [comment]
# brh.data-commons.org/manifest.json
## :warning: Services on branch
- revproxy

**Review by mfshao — APPROVED** [review]

**Pull request merged**
