### PR TITLE
chore(qa): Initial set up for Gen3 release 202002

### PR DESCRIPTION
**Pull request by themarcelor**
Introducing manifest.json & knownbugs.md files correspondent to the 1st Gen3 Core Release (`202002`). The files are stored in `cdis-manifest` for documentation purposes only (as per the official Gen3 Release doc).

Images tested through a gitops-qa PR:
https://github.com/uc-cdis/gitops-qa/pull/386

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# releases/2020/02/manifest.json
## :warning: Services on branch
- arborist
- fence
- indexd
- peregrine
- pidgin
- sheepdog
- portal
- tube
- guppy
- sower
- hatchery
- wts
- manifestservice
- dashboard

**Comment by PlanXCyborg** [comment]
# releases/2020/02/manifest.json
## :warning: Services on branch
- arborist
- dashboard
- hatchery
- fence
- indexd
- peregrine
- pidgin
- sheepdog
- portal
- ssjdispatcher
- tube
- guppy

**Comment by themarcelor** [comment]
We have to move this to `gitops-qa`. Closing this PR as per @frickjack 's instructions.

**Comment by PlanXCyborg** [comment]
# releases/2020/02/manifest.json
## :warning: Services on branch
- arborist
- dashboard
- hatchery
- fence
- indexd
- peregrine
- pidgin
- sheepdog
- portal
- ssjdispatcher
- tube
- guppy

**Comment by PlanXCyborg** [comment]
# releases/2020/02/manifest.json
## :warning: Services on branch
- arborist
- dashboard
- hatchery
- fence
- indexd
- peregrine
- pidgin
- sheepdog
- portal
- ssjdispatcher
- tube
- guppy

**Pull request merged**
