### PR TITLE
DCF RELEASE 1595265496

### PR DESCRIPTION
**Pull request by themarcelor**
copying files from nci-crdc-staging.datacommons.io to nci-crdc.datacommons.io

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# nci-crdc.datacommons.io/manifest.json
## Deployment changes
- indexd
  - Indexd's blank record endpoints now allow direct iteration from a user with their access token but requires the file upload arborist role to be modified so the service is not just `fence` but instead `*` so indexd works too. see https://github.com/uc-cdis/commons-users/pull/908/files for example (uc-cdis/uc-cdis/indexd#275)

**Comment by PlanXCyborg** [comment]
# nci-crdc.datacommons.io/manifest.json
## Deployment changes
- indexd
  - Indexd's blank record endpoints now allow direct iteration from a user with their access token but requires the file upload arborist role to be modified so the service is not just `fence` but instead `*` so indexd works too. see https://github.com/uc-cdis/commons-users/pull/908/files for example (uc-cdis/uc-cdis/indexd#275)

**Comment by PlanXCyborg** [comment]
# nci-crdc.datacommons.io/manifest.json
## Deployment changes
- indexd
  - Indexd's blank record endpoints now allow direct iteration from a user with their access token but requires the file upload arborist role to be modified so the service is not just `fence` but instead `*` so indexd works too. see https://github.com/uc-cdis/commons-users/pull/908/files for example (uc-cdis/uc-cdis/indexd#275)

**Comment by themarcelor** [comment]
Cancelling PR as DCF staging requires some GUI changes.

**Pull request closed without merging**
