### PR TITLE
feat/ibdGuppy: PXP-7121

### PR DESCRIPTION
**Pull request by ocshawn**
Link to Jira ticket if there is one:

### Environments
IBD

### Description of changes
- performance change to how guppy gets total count

### CODE REVIEW

**Review by paulineribeyre — APPROVED** [review]

**Comment by PlanXCyborg** [comment]
# ibdgc.datacommons.io
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: rowAccessor [project_id] not found in index with type project

**Comment by PlanXCyborg** [comment]
# ibdgc.datacommons.io
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: rowAccessor [project_id] not found in index with type project

**Comment by PlanXCyborg** [comment]
# ibdgc.datacommons.io
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: rowAccessor [project_id] not found in index with type project

**Comment by PlanXCyborg** [comment]
# ibdgc.datacommons.io
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: rowAccessor [project_id] not found in index with type project

**Pull request merged**
