### PR TITLE
chore(heal): enable aggregate MDS APIs for preprod

### PR DESCRIPTION
**Pull request by williamhaley**
Link to Jira ticket if there is one:

### Environments

* HEAL QA

### Description of changes

* Enable use of the aggregate MDS APIs

### CODE REVIEW

**Review by xritter1 — APPROVED** [review]

**Review by haraprasadj — APPROVED** [review]

**Comment by PlanXCyborg** [comment]
# preprod.healdata.org/manifest.json
## :warning: Services on branch
- metadata
- portal

**Comment by PlanXCyborg** [comment]
# preprod.healdata.org/manifest.json
## :warning: Services on branch
- metadata
- portal

**Comment by PlanXCyborg** [comment]
# preprod.healdata.org/manifest.json
## :warning: Services on branch
- metadata
- portal

**Comment by PlanXCyborg** [comment]
# preprod.healdata.org/manifest.json
## :warning: Services on branch
- metadata
- portal

**Comment by PlanXCyborg** [comment]
# preprod.healdata.org/manifest.json
## :warning: Services on branch
- hatchery
- metadata
- portal

**Pull request merged**
