### PR TITLE
chore(qa): Update acct.bionimbus.org with Gen3 Core Release release 2020.03

### PR DESCRIPTION
**Pull request by themarcelor**
Update acct.bionimbus.org with Gen3 Core Release release 2020.02

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# acct.bionimbus.org/manifest.json
## Deployment changes
- sheepdog
  - Fix Travis coverage reports (combine the results of all 3 tests into one coverage report). (uc-cdis/sheepdog#314)

**Comment by paulineribeyre** [comment]
# acct.bionimbus.org/manifest.json
## Deployment changes
- sheepdog
  - Fix Travis coverage reports (combine the results of all 3 tests into one coverage report). (uc-cdis/sheepdog#314)

**Comment by paulineribeyre** [comment]
# acct.bionimbus.org/manifest.json
## :warning: Services on branch
- arborist
- fence
- indexd
- peregrine
- pidgin
- sheepdog
- portal

**Comment by PlanXCyborg** [comment]
# acct.bionimbus.org/manifest.json
## :warning: Services on branch
- arborist
- fence
- indexd
- peregrine
- pidgin
- sheepdog
- portal
## Deployment changes
- sheepdog
  - Fix Travis coverage reports (combine the results of all 3 tests into one coverage report). (uc-cdis/sheepdog#314)

**Comment by PlanXCyborg** [comment]
# acct.bionimbus.org/manifest.json
## :warning: Services on branch
- arborist
- fence
- indexd
- peregrine
- pidgin
- sheepdog
- portal
## Deployment changes
- sheepdog
  - Fix Travis coverage reports (combine the results of all 3 tests into one coverage report). (uc-cdis/sheepdog#314)

**Comment by PlanXCyborg** [comment]
# acct.bionimbus.org/manifest.json
## Deployment changes
- sheepdog
  - Fix Travis coverage reports (combine the results of all 3 tests into one coverage report). (uc-cdis/sheepdog#314)

**Comment by PlanXCyborg** [comment]
# acct.bionimbus.org/manifest.json
## :warning: Services on branch
- arborist
- fence
- indexd
- peregrine
- pidgin
- sheepdog
- portal

**Comment by PlanXCyborg** [comment]
# acct.bionimbus.org/manifest.json
## Deployment changes
- fence
  - In fence-config, the region field of S3_BUCKETS is now required: if not specified, Fence will print a warning and try to call GetBucketLocation. Fence will error at startup if that doesn't work. (uc-cdis/fence#749)
- portal
  - New optional `title` parameter in Terra Export Warning configuration: `terraExportWarning: { subjectThreshold: int, title: string(optional), message: string(optional) }` (uc-cdis/portal#656)
  - Added `terraExportWarning: { subjectThreshold: <number>, message: <string, optional> }` to portal config. (uc-cdis/portal#642)
  - New optional portal config flag: dataExplorerConfig.terraTemplate. The value of this parameter is placed in the Terra export URL as the value of the query parameter 'template'. (uc-cdis/portal#645)
- sheepdog
  - Fix Travis coverage reports (combine the results of all 3 tests into one coverage report). (uc-cdis/sheepdog#314)

**Pull request merged**
