### PR TITLE
Chore/brh prod wts at login

### PR DESCRIPTION
**Pull request by nss10**
Link to Jira ticket if there is one: [BRH-345](https://ctds-planx.atlassian.net/browse/BRH-345)

### Environments
* BRH-Prod

### Description of changes
* Added `workspaceTokenServiceRefreshTokenAtLogin` and updated portal to `5.2.0` to test `data-portal PR-1095`

[BRH-345]: https://ctds-planx.atlassian.net/browse/BRH-345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by nss10** [comment]
Need to merge and test  [PR-5536](https://github.com/uc-cdis/cdis-manifest/pull/5536) before merging this.

**Comment by PlanXCyborg** [comment]
# brh.data-commons.org/manifest.json
## Deployment changes
- portal
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)

**Comment by PlanXCyborg** [comment]
# brh.data-commons.org/manifest.json
## Deployment changes
- portal
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)

**Review by briennal — APPROVED** [review]

**Comment by PlanXCyborg** [comment]
# brh.data-commons.org/manifest.json
## Deployment changes
- portal
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)

**Comment by PlanXCyborg** [comment]
# brh.data-commons.org/manifest.json
## Deployment changes
- portal
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)

**Pull request merged**
