### PR TITLE
deploy centralized auth to kf prod

### PR DESCRIPTION
**Pull request by diw2**

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# data.kidsfirstdrc.org/manifest.json
## Deployment changes
- arborist
  - Assuming any commons running Arborist < 2.3 was using user sync only as AuthZ provider (uc-cdis/arborist#111)
  - One-off: Update authz_provider to the correct values (uc-cdis/arborist#109)
  - Database deployment (uc-cdis/arborist#42)
  - See `migrations` folder for database schema and setup utilities (uc-cdis/arborist#42)
- fence
  - Fence config ENABLED_IDENTITY_PROVIDERS section deprecated and replaced by LOGIN_OPTIONS section to allow enabling several login options for the same provider (backwards compatible) (uc-cdis/fence#703)
  - Requires manual work in Arborist DB to fill in the empty `authz_provider` fields (uc-cdis/fence#696)
  - new cloud automation job for database migration https://github.com/uc-cdis/cloud-automation/pull/977 (uc-cdis/fence#694)
  - configuration added for requester pays Google Buckets. if this is needed, you'll need to update configuration. default config does not support requester pays bucket access (uc-cdis/fence#668)
- indexd
  - Add script to run for filling out records' `authz` fields based on the `acl` fields. (uc-cdis/indexd#218)
  - cc @david4096 (uc-cdis/indexd#188)
  - The database table `index_record_ace`'s primary key is (did, acl), so we shouldn't allow duplicates in the ACL list when making an IndexRecord. Using a set removes the duplicates. (uc-cdis/indexd#198)
- peregrine
  - ARBORIST_URL environment variable replaces broken default ARBORIST config variable (uc-cdis/peregrine#142)
  - Optional configuration variable ARBORIST (arborist base URL) (uc-cdis/peregrine#138)
  - Requires Arborist to be deployed (uc-cdis/peregrine#138)
  - look for INDEX_CLIENT instead of SIGNPOST in app.config (uc-cdis/peregrine#135)
  - get INDEX_CLIENT_HOST env var instead of SIGNPOST_HOST (uc-cdis/peregrine#135)
- pidgin
  - added required configuration variable "API_HEALTH_URL" for status endpoint (uc-cdis/pidgin#31)
  - use the latest version of the python 3 base image (uc-cdis/pidgin#29)
  - The Dockerfile now uses an Alpine image (uc-cdis/pidgin#24)
- portal
  - InCommon login needs fence 4.8.0 (uc-cdis/portal#595)
  - Need Guppy 0.3.7+ to handle large file size (uc-cdis/portal#603)
  - if deployed with "useArboristUI": true, needs Arborist's GET /auth/mapping endpoint to be exposed via revproxy. (useArboristUI false by default) (uc-cdis/portal#592)
  - New optional portal config field called `adminPreAppliedFilters`. Goes in data/config/*.json. (uc-cdis/portal#576)
  - For a "cert" if the required document is a quiz, then hasCorrectAnswers should be true, otherwise false. (uc-cdis/portal#571)
  - Windmill lists unmapped files by checking Indexd. Before centralized auth's deployment, a file was determined to be unmapped by checking if the acl field was null. After centralized auth, we use the authz field instead. The new manifest configuration setting `use_indexd_authz` in the global block specifies which of the two fields should be used. This field defaults to false. (uc-cdis/portal#570)
  - Deployed in https://qa-canine.planx-pla.net with fence version < 3, index authz field set to false (uc-cdis/portal#570)
  - (by default). (uc-cdis/portal#570)
  - Deployed in https://qa-brain.planx-pla.net with fence version > 3, index authz field set to true. (uc-cdis/portal#570)
  - New portal configuration and images for AnVIL (uc-cdis/portal#569)
  - Requires a url to be specified in `dataExplorerConfig` called `terraExportURL` (uc-cdis/portal#568)
  - This should be `bvdp-saturn-${env}.appspot.com/#import-data`, where `${env}` is `dev`, `staging`, or `prod` (uc-cdis/portal#568)
  - Needs a version of cloud-automation that exposes arborist's `auth/proxy` endpoint (uc-cdis/portal#565)
  - fixed DAT requires Guppy >= 0.3.1 (uc-cdis/portal#563)
  - DAT requires Guppy >= 0.3.0 (uc-cdis/portal#561)
  - This change requires `sower` version >= `0.3.0`. (uc-cdis/portal#562)
  - This PR requires https://github.com/uc-cdis/guppy/pull/45 (0.2.1+) if want to use Guppy for NIAID (uc-cdis/portal#558)
  - require `fileExplorerConfig` block with `buttons` (uc-cdis/portal#554)
  - New manifest.json variable: logout_inactive_users. Defaults to true if not provided. (uc-cdis/portal#526)
  - https://github.com/uc-cdis/cloud-automation/pull/818 (uc-cdis/portal#526)
  - enable source map tool so that developers could have better debugging under dev mode (uc-cdis/portal#514)
  - Fix warning from fsevents packages during docker image building (uc-cdis/portal#488)
  - Add flag to `npm ci` in dockerfile to support npm prepared files from `ui-component` library (uc-cdis/portal#488)
  - Workspace button in DCF Sandbox (uc-cdis/portal#466)
- sheepdog
  - ARBORIST_URL environment variable replaces broken default ARBORIST config variable (uc-cdis/sheepdog#304)
  - Optional configuration variable `ARBORIST` (arborist base URL) (uc-cdis/sheepdog#298)
  - Requires Arborist to be deployed (uc-cdis/sheepdog#298)
  - look for INDEX_CLIENT instead of SIGNPOST in app.config (uc-cdis/sheepdog#291)
  - get INDEX_CLIENT_HOST env var instead of SIGNPOST_HOST (uc-cdis/sheepdog#291)

**Comment by PlanXCyborg** [comment]
# data.kidsfirstdrc.org/manifest.json
## Deployment changes
- arborist
  - Assuming any commons running Arborist < 2.3 was using user sync only as AuthZ provider (uc-cdis/arborist#111)
  - One-off: Update authz_provider to the correct values (uc-cdis/arborist#109)
  - Database deployment (uc-cdis/arborist#42)
  - See `migrations` folder for database schema and setup utilities (uc-cdis/arborist#42)
- fence
  - Fence config ENABLED_IDENTITY_PROVIDERS section deprecated and replaced by LOGIN_OPTIONS section to allow enabling several login options for the same provider (backwards compatible) (uc-cdis/fence#703)
  - Requires manual work in Arborist DB to fill in the empty `authz_provider` fields (uc-cdis/fence#696)
  - new cloud automation job for database migration https://github.com/uc-cdis/cloud-automation/pull/977 (uc-cdis/fence#694)
  - configuration added for requester pays Google Buckets. if this is needed, you'll need to update configuration. default config does not support requester pays bucket access (uc-cdis/fence#668)
- indexd
  - Add script to run for filling out records' `authz` fields based on the `acl` fields. (uc-cdis/indexd#218)
  - cc @david4096 (uc-cdis/indexd#188)
  - The database table `index_record_ace`'s primary key is (did, acl), so we shouldn't allow duplicates in the ACL list when making an IndexRecord. Using a set removes the duplicates. (uc-cdis/indexd#198)
- peregrine
  - ARBORIST_URL environment variable replaces broken default ARBORIST config variable (uc-cdis/peregrine#142)
  - Optional configuration variable ARBORIST (arborist base URL) (uc-cdis/peregrine#138)
  - Requires Arborist to be deployed (uc-cdis/peregrine#138)
  - look for INDEX_CLIENT instead of SIGNPOST in app.config (uc-cdis/peregrine#135)
  - get INDEX_CLIENT_HOST env var instead of SIGNPOST_HOST (uc-cdis/peregrine#135)
- pidgin
  - added required configuration variable "API_HEALTH_URL" for status endpoint (uc-cdis/pidgin#31)
  - use the latest version of the python 3 base image (uc-cdis/pidgin#29)
  - The Dockerfile now uses an Alpine image (uc-cdis/pidgin#24)
- portal
  - InCommon login needs fence 4.8.0 (uc-cdis/portal#595)
  - Need Guppy 0.3.7+ to handle large file size (uc-cdis/portal#603)
  - if deployed with "useArboristUI": true, needs Arborist's GET /auth/mapping endpoint to be exposed via revproxy. (useArboristUI false by default) (uc-cdis/portal#592)
  - New optional portal config field called `adminPreAppliedFilters`. Goes in data/config/*.json. (uc-cdis/portal#576)
  - For a "cert" if the required document is a quiz, then hasCorrectAnswers should be true, otherwise false. (uc-cdis/portal#571)
  - Windmill lists unmapped files by checking Indexd. Before centralized auth's deployment, a file was determined to be unmapped by checking if the acl field was null. After centralized auth, we use the authz field instead. The new manifest configuration setting `use_indexd_authz` in the global block specifies which of the two fields should be used. This field defaults to false. (uc-cdis/portal#570)
  - Deployed in https://qa-canine.planx-pla.net with fence version < 3, index authz field set to false (uc-cdis/portal#570)
  - (by default). (uc-cdis/portal#570)
  - Deployed in https://qa-brain.planx-pla.net with fence version > 3, index authz field set to true. (uc-cdis/portal#570)
  - New portal configuration and images for AnVIL (uc-cdis/portal#569)
  - Requires a url to be specified in `dataExplorerConfig` called `terraExportURL` (uc-cdis/portal#568)
  - This should be `bvdp-saturn-${env}.appspot.com/#import-data`, where `${env}` is `dev`, `staging`, or `prod` (uc-cdis/portal#568)
  - Needs a version of cloud-automation that exposes arborist's `auth/proxy` endpoint (uc-cdis/portal#565)
  - fixed DAT requires Guppy >= 0.3.1 (uc-cdis/portal#563)
  - DAT requires Guppy >= 0.3.0 (uc-cdis/portal#561)
  - This change requires `sower` version >= `0.3.0`. (uc-cdis/portal#562)
  - This PR requires https://github.com/uc-cdis/guppy/pull/45 (0.2.1+) if want to use Guppy for NIAID (uc-cdis/portal#558)
  - require `fileExplorerConfig` block with `buttons` (uc-cdis/portal#554)
  - New manifest.json variable: logout_inactive_users. Defaults to true if not provided. (uc-cdis/portal#526)
  - https://github.com/uc-cdis/cloud-automation/pull/818 (uc-cdis/portal#526)
  - enable source map tool so that developers could have better debugging under dev mode (uc-cdis/portal#514)
  - Fix warning from fsevents packages during docker image building (uc-cdis/portal#488)
  - Add flag to `npm ci` in dockerfile to support npm prepared files from `ui-component` library (uc-cdis/portal#488)
  - Workspace button in DCF Sandbox (uc-cdis/portal#466)
- sheepdog
  - ARBORIST_URL environment variable replaces broken default ARBORIST config variable (uc-cdis/sheepdog#304)
  - Optional configuration variable `ARBORIST` (arborist base URL) (uc-cdis/sheepdog#298)
  - Requires Arborist to be deployed (uc-cdis/sheepdog#298)
  - look for INDEX_CLIENT instead of SIGNPOST in app.config (uc-cdis/sheepdog#291)
  - get INDEX_CLIENT_HOST env var instead of SIGNPOST_HOST (uc-cdis/sheepdog#291)

**Comment by PlanXCyborg** [comment]
# data.kidsfirstdrc.org/manifest.json
## Deployment changes
- arborist
  - Assuming any commons running Arborist < 2.3 was using user sync only as AuthZ provider (uc-cdis/arborist#111)
  - One-off: Update authz_provider to the correct values (uc-cdis/arborist#109)
  - Database deployment (uc-cdis/arborist#42)
  - See `migrations` folder for database schema and setup utilities (uc-cdis/arborist#42)
- fence
  - Fence config ENABLED_IDENTITY_PROVIDERS section deprecated and replaced by LOGIN_OPTIONS section to allow enabling several login options for the same provider (backwards compatible) (uc-cdis/fence#703)
  - Requires manual work in Arborist DB to fill in the empty `authz_provider` fields (uc-cdis/fence#696)
  - new cloud automation job for database migration https://github.com/uc-cdis/cloud-automation/pull/977 (uc-cdis/fence#694)
  - configuration added for requester pays Google Buckets. if this is needed, you'll need to update configuration. default config does not support requester pays bucket access (uc-cdis/fence#668)
- indexd
  - Add script to run for filling out records' `authz` fields based on the `acl` fields. (uc-cdis/indexd#218)
  - cc @david4096 (uc-cdis/indexd#188)
  - The database table `index_record_ace`'s primary key is (did, acl), so we shouldn't allow duplicates in the ACL list when making an IndexRecord. Using a set removes the duplicates. (uc-cdis/indexd#198)
- peregrine
  - ARBORIST_URL environment variable replaces broken default ARBORIST config variable (uc-cdis/peregrine#142)
  - Optional configuration variable ARBORIST (arborist base URL) (uc-cdis/peregrine#138)
  - Requires Arborist to be deployed (uc-cdis/peregrine#138)
  - look for INDEX_CLIENT instead of SIGNPOST in app.config (uc-cdis/peregrine#135)
  - get INDEX_CLIENT_HOST env var instead of SIGNPOST_HOST (uc-cdis/peregrine#135)
- pidgin
  - added required configuration variable "API_HEALTH_URL" for status endpoint (uc-cdis/pidgin#31)
  - use the latest version of the python 3 base image (uc-cdis/pidgin#29)
  - The Dockerfile now uses an Alpine image (uc-cdis/pidgin#24)
- portal
  - InCommon login needs fence 4.8.0 (uc-cdis/portal#595)
  - Need Guppy 0.3.7+ to handle large file size (uc-cdis/portal#603)
  - if deployed with "useArboristUI": true, needs Arborist's GET /auth/mapping endpoint to be exposed via revproxy. (useArboristUI false by default) (uc-cdis/portal#592)
  - New optional portal config field called `adminPreAppliedFilters`. Goes in data/config/*.json. (uc-cdis/portal#576)
  - For a "cert" if the required document is a quiz, then hasCorrectAnswers should be true, otherwise false. (uc-cdis/portal#571)
  - Windmill lists unmapped files by checking Indexd. Before centralized auth's deployment, a file was determined to be unmapped by checking if the acl field was null. After centralized auth, we use the authz field instead. The new manifest configuration setting `use_indexd_authz` in the global block specifies which of the two fields should be used. This field defaults to false. (uc-cdis/portal#570)
  - Deployed in https://qa-canine.planx-pla.net with fence version < 3, index authz field set to false (uc-cdis/portal#570)
  - (by default). (uc-cdis/portal#570)
  - Deployed in https://qa-brain.planx-pla.net with fence version > 3, index authz field set to true. (uc-cdis/portal#570)
  - New portal configuration and images for AnVIL (uc-cdis/portal#569)
  - Requires a url to be specified in `dataExplorerConfig` called `terraExportURL` (uc-cdis/portal#568)
  - This should be `bvdp-saturn-${env}.appspot.com/#import-data`, where `${env}` is `dev`, `staging`, or `prod` (uc-cdis/portal#568)
  - Needs a version of cloud-automation that exposes arborist's `auth/proxy` endpoint (uc-cdis/portal#565)
  - fixed DAT requires Guppy >= 0.3.1 (uc-cdis/portal#563)
  - DAT requires Guppy >= 0.3.0 (uc-cdis/portal#561)
  - This change requires `sower` version >= `0.3.0`. (uc-cdis/portal#562)
  - This PR requires https://github.com/uc-cdis/guppy/pull/45 (0.2.1+) if want to use Guppy for NIAID (uc-cdis/portal#558)
  - require `fileExplorerConfig` block with `buttons` (uc-cdis/portal#554)
  - New manifest.json variable: logout_inactive_users. Defaults to true if not provided. (uc-cdis/portal#526)
  - https://github.com/uc-cdis/cloud-automation/pull/818 (uc-cdis/portal#526)
  - enable source map tool so that developers could have better debugging under dev mode (uc-cdis/portal#514)
  - Fix warning from fsevents packages during docker image building (uc-cdis/portal#488)
  - Add flag to `npm ci` in dockerfile to support npm prepared files from `ui-component` library (uc-cdis/portal#488)
  - Workspace button in DCF Sandbox (uc-cdis/portal#466)
- sheepdog
  - ARBORIST_URL environment variable replaces broken default ARBORIST config variable (uc-cdis/sheepdog#304)
  - Optional configuration variable `ARBORIST` (arborist base URL) (uc-cdis/sheepdog#298)
  - Requires Arborist to be deployed (uc-cdis/sheepdog#298)
  - look for INDEX_CLIENT instead of SIGNPOST in app.config (uc-cdis/sheepdog#291)
  - get INDEX_CLIENT_HOST env var instead of SIGNPOST_HOST (uc-cdis/sheepdog#291)

**Comment by paulineribeyre** [comment]
the only failing test is a sheepdog test that was also failing in QA and Staging, seems to be related to outdated versions (PXP-5191) - we don't use sheepdog in KF which is why we are ignoring it.

**Pull request merged**
